#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/wmake/scripts/AllwmakeParseArguments

#------------------------------------------------------------------------------

if [ -d "${FASTDUALOCTREE_SRC_PATH}" ]
then
    wmake $targetType
fi

#------------------------------------------------------------------------------
