#!/bin/sh
cd ${0%/*} || exit 1                        # Run from this directory
. $WM_PROJECT_DIR/wmake/scripts/AllwmakeParseArguments # (for error catching)

#------------------------------------------------------------------------------

if [ -d "${FASTDUALOCTREE_SRC_PATH}" ]
then
    wmake $targetType
fi

#------------------------------------------------------------------------------
