#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Set application name
application="buoyantSimpleFoam"

runApplication blockMesh
runApplication $application
runApplication sample -latestTime
(cd validation && ./createGraphs)
