#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

# remove old time and post-processing directories
\rm -rf 0 *[1-9]* processor* postProcessing

# restore 0/ directory from 0.org/
\cp -r 0.org 0

cleanCase

#------------------------------------------------------------------------------
