#!/bin/sh
cd ${0%/*} || exit 1                        # Run from this directory
. $WM_PROJECT_DIR/bin/tools/RunFunctions    # Tutorial run functions

restore0Dir

runApplication blockMesh

runApplication potentialFoam

# Remove incompatible (volumetric) flux field
\rm -f 0/phi 2>/dev/null

runApplication decomposePar

runParallel $(getApplication)

#------------------------------------------------------------------------------
