// Compatibility include. For v2006 and earlier

#ifndef FoamCompat_tmpNrc_H
#define FoamCompat_tmpNrc_H

#include "refPtr.H"

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

namespace Foam
{
    //- Deprecated(2020-07) - use refPtr instead
    //  \deprecated(2020-07) - use refPtr instead
    typedef refPtr tmpNrc;
}

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //
