#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
[ $# -ge 1 ] && makeOption=$1 || makeOption=libso
set -x

wmake $makeOption specie
wmake $makeOption solid
wmake $makeOption thermophysicalFunctions
./properties/Allwmake $*

wmake $makeOption basic
wmake $makeOption reactionThermo
wmake $makeOption laminarFlameSpeed
wmake $makeOption chemistryModel
wmake $makeOption pdfs
wmake $makeOption radiationModels
wmake $makeOption barotropicCompressibilityModel
wmake $makeOption thermalPorousZone

wmake $makeOption SLGThermo

# Should be combined with solids&solidMixture
wmake $makeOption basicSolidThermo


# ----------------------------------------------------------------- end-of-file
