#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x

wmake libso specie
wmake libso solid
wmake libso thermophysicalFunctions
wmake libso liquids
wmake libso liquidMixture
wmake libso pointSolids
wmake libso pointSolidMixture

wmake libso basic
wmake libso reactionThermo
wmake libso laminarFlameSpeed
wmake libso chemistryModel
wmake libso pdfs
wmake libso radiation
wmake libso barotropicCompressibilityModel
wmake libso thermalPorousZone

wmake libso SLGThermo

# Should be combined with solids&solidMixture
wmake libso basicSolidThermo


# ----------------------------------------------------------------- end-of-file
