#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

runApplication ansysToFoam flange.ans -scale 0.001
runApplication $(getApplication)
runApplication foamToEnsight -noZero
runApplication foamToVTK

#------------------------------------------------------------------------------
