#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

mkdir -p constant/triSurface

cp -f \
    resources/geometry/curvature-box.stl.gz \
    constant/triSurface

runApplication surfaceFeatureExtract

runApplication blockMesh

runApplication snappyHexMesh -overwrite

#------------------------------------------------------------------------------
