#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
. ${WM_PROJECT_DIR:?}/bin/tools/CleanFunctions      # Tutorial clean functions
#------------------------------------------------------------------------------

(cd eulerianInjection && ./Allclean)

if notTest $@
then
    (cd lagrangianParticleInjection && ./Allclean)
    (cd lagrangianDistributionInjection && ./Allclean)
fi

#------------------------------------------------------------------------------
