#!/bin/sh

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

restore0Dir

runApplication blockMesh

\cp 0/alpha.water.org 0/alpha.water

runApplication setFields

runApplication $(getApplication)
