#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Parse arguments for library compilation
. $WM_PROJECT_DIR/wmake/scripts/AllwmakeParseArguments

if [ -f "$CGAL_ARCH_PATH/include/CGAL/version.h" ] || \
   [ "${CGAL_ARCH_PATH##*-}" = system -a -f /usr/include/CGAL/version.h ]
then
    wmake $targetType conformalVoronoiMesh
    wmake $targetType conformalVoronoi2DMesh
    wmake foamyQuadMesh
    wmake foamyHexMesh
    # wmake foamyHexMeshBackgroundMesh
    # (cd foamyHexMeshSurfaceSimplify && ./Allwmake)
    # wmake cellSizeAndAlignmentGrid
else
    echo "WARNING: cannot build ${PWD##*/} without CGAL"
fi

#------------------------------------------------------------------------------
