#!/bin/sh

# Get application name from directory
parentDir=`dirname $PWD`
application=`basename $parentDir`

# Find and source additional functions
tutorialPath=$PWD
while [ ! -f $tutorialPath/RunFunctions ]
do
    tutorialPath="$tutorialPath/.."
done
. $tutorialPath/RunFunctions



runApplication blockMesh
runApplication setFields
runApplication $application
