#!/bin/sh

# Get application name from directory
parentDir=`dirname $PWD`
application=`basename $parentDir`

# Find and source additional functions
tutorialPath=$PWD
while [ ! -f $tutorialPath/CleanFunctions ]
do
    tutorialPath="$tutorialPath/.."
done
. $tutorialPath/CleanFunctions



mv ./-180 temp180
rm -rf 0
cp system/controlDict.1st system/controlDict
cleanCase
mv temp180 ./-180
