#!/bin/sh
set -x

# Some fun: prostar uses ccmio2.3, Star-ccm+ uses ccmio2.4

(cd libccmio; wmake libso libadf)
(cd libccmio; wmake libso libccmio)
(cd libccmio; wmake libso libcgns)
(cd ccm26ToFoam; wmake)
