#!/bin/sh
cd ${0%/*} || exit 1                        # Run from this directory
. $WM_PROJECT_DIR/bin/tools/RunFunctions    # Tutorial run functions

./Allrun.pre

# Serial
#runApplication $(getApplication)

# Parallel
runApplication decomposePar -cellDist
runParallel  $(getApplication)

#------------------------------------------------------------------------------
