#!/bin/sh
# Build optional components (eg, may depend on third-party libraries)
set -x

# if the library exists, assume there are headers too
if [ -e $FOAM_LIBBIN/libccmio.so ]
then
   wmake ccm26ToFoam
fi

# end
