#!/bin/sh
cd ${0%/*} || exit 1                        # Run from this directory
. $WM_PROJECT_DIR/bin/tools/RunFunctions    # Tutorial run functions

# Do the Spalart-Allmaras steady-state case
(cd motorBike && foamRunTutorials)

if notTest $@
then
    # Clone the steady-state case to the LES case
    cloneParallelCase motorBike motorBikeLES

    # Do the LES case
    \cp lesFiles/Allrun motorBikeLES/
    (cd motorBikeLES && foamRunTutorials)
fi

#------------------------------------------------------------------------------
