#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application name from directory
application="XiFoam"

cases=" \
pitzDaily \
pitzDaily3D
"

for i in $cases; do
    blockMesh -case $i
    $application -case $i
done

