#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
#-----------------------------------------------------------------------------

(cd overset-1 && ./Allclean)

(cd overset-2 && ./Allclean)

(cd background && ./Allclean)

#------------------------------------------------------------------------------