#!/bin/sh
cd "${0%/*}" || exit    # Run from this directory

foamCleanTutorials -self
rm -rf 0/alpha.water 0/alpha.water.gz 0/T.air.gz 0/T.water.gz \
    probes wallPressure pRefProbe

#------------------------------------------------------------------------------
