#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
#------------------------------------------------------------------------------

(cd code && ./Allclean)

(cd steady && ./Allclean)

rm -rf movement
rm -rf transient

#------------------------------------------------------------------------------
