#!/bin/sh
cd ${0%/*} || exit 1                        # Run from this directory

rm log.* 2>/dev/null                        # No application, clean manually

#------------------------------------------------------------------------------
