#!/bin/sh
# Allwmake with scan-build (clang)

c_compiler="$(command -v "$(wmake -show-c)")"
cxx_compiler="$(command -v "$(wmake -show-cxx)")"

set -x

scan-build --use-cc="$c_compiler" --use-c++="$cxx_compiler" \
    ./Allwmake "$@"

#------------------------------------------------------------------------------
