#!/bin/sh
# Allwmake with scan-build (clang)

c_compiler="$(command -v $WM_CC)"
cxx_compiler"$(command -v $WM_CXX)"

set -x

scan-build --use-cc="$c_compiler" --use-c++="$cxx_compiler" \
    ./Allwmake "$@"

#------------------------------------------------------------------------------
