#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x

wmake libso extrudeModel
wmake extrudeMesh

wmake libso extrudeToRegionMesh/createShellMesh
wmake extrudeToRegionMesh


# ----------------------------------------------------------------- end-of-file
