#!/bin/sh
cd "${0%/*}" || exit    # Run from this directory

wclean turbulenceModels
wclean incompressible
wclean compressible
wclean schemes
wcleanLnIncludeAll

#------------------------------------------------------------------------------
