#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/CleanFunctions      # Tutorial clean functions
#------------------------------------------------------------------------------

cleanCase0

rm -rf constant/boundaryData
rm -f constant/faMesh/faceLabels
rm -f constant/faMesh/faBoundary
rm -rf constant/triSurface

# -----------------------------------------------------------------------------
