#!/bin/sh
cd ${0%/*} || exit 1                        # Run from this directory
. $WM_PROJECT_DIR/bin/tools/CleanFunctions  # Tutorial clean functions

cleanCase0

# Remove surface and features
\rm -f  constant/triSurface/motorBike.obj.gz > /dev/null 2>&1
\rm -f  constant/triSurface/motorBike.eMesh  > /dev/null 2>&1
\rm -rf constant/extendedFeatureEdgeMesh     > /dev/null 2>&1

\cp system/controlDict_run system/controlDict

#------------------------------------------------------------------------------
