#!/bin/sh

currDir=`pwd`
application=`basename $currDir`
cases="boundaryWallFunctions boundaryLaunderSharma"

tutorialPath=`dirname $0`/..
. $tutorialPath/CleanFunctions

for case in $cases
do
    cleanCase $case
done 
