#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Reset the controlDict
if [ -f system/controlDict.orig ]
then
    echo "$0: restoring the controlDict from controlDict.orig"
    mv system/controlDict.orig system/controlDict
fi

./Allrun

#------------------------------------------------------------------------------
