#define TOK_QUESTION                         1
#define TOK_COLON                            2
#define TOK_LOR                              3
#define TOK_LAND                             4
#define TOK_BIT_XOR                          5
#define TOK_BIT_AND                          6
#define TOK_EQUAL                            7
#define TOK_NOT_EQUAL                        8
#define TOK_LESS_EQ                          9
#define TOK_GREATER_EQ                      10
#define TOK_LESS                            11
#define TOK_GREATER                         12
#define TOK_PLUS                            13
#define TOK_MINUS                           14
#define TOK_TIMES                           15
#define TOK_DIVIDE                          16
#define TOK_PERCENT                         17
#define TOK_NEGATE                          18
#define TOK_NOT                             19
#define TOK_DOT                             20
#define TOK_NUMBER                          21
#define TOK_ZERO                            22
#define TOK_PI                              23
#define TOK_LPAREN                          24
#define TOK_RPAREN                          25
#define TOK_DEG_TO_RAD                      26
#define TOK_RAD_TO_DEG                      27
#define TOK_ARG                             28
#define TOK_TIME                            29
#define TOK_DELTA_T                         30
#define TOK_SCALAR_ID                       31
#define TOK_SSCALAR_ID                      32
#define TOK_INTERNAL_FIELD                  33
#define TOK_NEIGHBOUR_FIELD                 34
#define TOK_SN_GRAD                         35
#define TOK_MIN                             36
#define TOK_COMMA                           37
#define TOK_MAX                             38
#define TOK_SUM                             39
#define TOK_AVERAGE                         40
#define TOK_EXP                             41
#define TOK_LOG                             42
#define TOK_LOG10                           43
#define TOK_SQR                             44
#define TOK_SQRT                            45
#define TOK_CBRT                            46
#define TOK_SIN                             47
#define TOK_COS                             48
#define TOK_TAN                             49
#define TOK_ASIN                            50
#define TOK_ACOS                            51
#define TOK_ATAN                            52
#define TOK_SINH                            53
#define TOK_COSH                            54
#define TOK_TANH                            55
#define TOK_POW                             56
#define TOK_ATAN2                           57
#define TOK_POS                             58
#define TOK_NEG                             59
#define TOK_POS0                            60
#define TOK_NEG0                            61
#define TOK_SIGN                            62
#define TOK_FLOOR                           63
#define TOK_CEIL                            64
#define TOK_ROUND                           65
#define TOK_HYPOT                           66
#define TOK_RAND                            67
#define TOK_VECTOR_ID                       68
#define TOK_SVECTOR_ID                      69
#define TOK_SPH_TENSOR_ID                   70
#define TOK_SSPH_TENSOR_ID                  71
#define TOK_SYM_TENSOR_ID                   72
#define TOK_SSYM_TENSOR_ID                  73
#define TOK_IDENTITY_TENSOR                 74
#define TOK_TENSOR_ID                       75
#define TOK_STENSOR_ID                      76
#define TOK_LTRUE                           77
#define TOK_LFALSE                          78
#define TOK_BOOL                            79
#define TOK_SBOOL_ID                        80
#define TOK_FACE_AREA                       81
#define TOK_FACE_EXPR                       82
#define TOK_WEIGHT_AVERAGE                  83
#define TOK_WEIGHT_SUM                      84
#define TOK_POINT_EXPR                      85
#define TOK_PSCALAR_ID                      86
#define TOK_PVECTOR_ID                      87
#define TOK_PSPH_TENSOR_ID                  88
#define TOK_PSYM_TENSOR_ID                  89
#define TOK_PTENSOR_ID                      90
#define TOK_PBOOL_ID                        91
#define TOK_POINTS                          92
#define TOK_MAG                             93
#define TOK_MAGSQR                          94
#define TOK_VECTOR                          95
#define TOK_TENSOR                          96
#define TOK_SYM_TENSOR                      97
#define TOK_SPH_TENSOR                      98
#define TOK_CMPT_X                          99
#define TOK_CMPT_Y                         100
#define TOK_CMPT_Z                         101
#define TOK_CMPT_XX                        102
#define TOK_CMPT_XY                        103
#define TOK_CMPT_XZ                        104
#define TOK_CMPT_YX                        105
#define TOK_CMPT_YY                        106
#define TOK_CMPT_YZ                        107
#define TOK_CMPT_ZX                        108
#define TOK_CMPT_ZY                        109
#define TOK_CMPT_ZZ                        110
#define TOK_CMPT_II                        111
#define TOK_TRANSPOSE                      112
#define TOK_DIAG                           113
#define TOK_POINT_TO_FACE                  114
#define TOK_FACE_TO_POINT                  115
