#define TOK_QUESTION                         1
#define TOK_COLON                            2
#define TOK_LOR                              3
#define TOK_LAND                             4
#define TOK_BIT_XOR                          5
#define TOK_BIT_AND                          6
#define TOK_EQUAL                            7
#define TOK_NOT_EQUAL                        8
#define TOK_LESS_EQ                          9
#define TOK_GREATER_EQ                      10
#define TOK_LESS                            11
#define TOK_GREATER                         12
#define TOK_PLUS                            13
#define TOK_MINUS                           14
#define TOK_TIMES                           15
#define TOK_DIVIDE                          16
#define TOK_PERCENT                         17
#define TOK_NEGATE                          18
#define TOK_NOT                             19
#define TOK_DOT                             20
#define TOK_NUMBER                          21
#define TOK_ZERO                            22
#define TOK_PI                              23
#define TOK_LPAREN                          24
#define TOK_RPAREN                          25
#define TOK_DEG_TO_RAD                      26
#define TOK_RAD_TO_DEG                      27
#define TOK_TIME                            28
#define TOK_SCALAR_ID                       29
#define TOK_SSCALAR_ID                      30
#define TOK_MIN                             31
#define TOK_COMMA                           32
#define TOK_MAX                             33
#define TOK_SUM                             34
#define TOK_AVERAGE                         35
#define TOK_EXP                             36
#define TOK_LOG                             37
#define TOK_LOG10                           38
#define TOK_SQR                             39
#define TOK_SQRT                            40
#define TOK_CBRT                            41
#define TOK_SIN                             42
#define TOK_COS                             43
#define TOK_TAN                             44
#define TOK_ASIN                            45
#define TOK_ACOS                            46
#define TOK_ATAN                            47
#define TOK_SINH                            48
#define TOK_COSH                            49
#define TOK_TANH                            50
#define TOK_POW                             51
#define TOK_ATAN2                           52
#define TOK_POS                             53
#define TOK_NEG                             54
#define TOK_POS0                            55
#define TOK_NEG0                            56
#define TOK_SIGN                            57
#define TOK_FLOOR                           58
#define TOK_CEIL                            59
#define TOK_ROUND                           60
#define TOK_HYPOT                           61
#define TOK_RAND                            62
#define TOK_VECTOR_ID                       63
#define TOK_SVECTOR_ID                      64
#define TOK_SPH_TENSOR_ID                   65
#define TOK_SSPH_TENSOR_ID                  66
#define TOK_SYM_TENSOR_ID                   67
#define TOK_SSYM_TENSOR_ID                  68
#define TOK_UNIT_TENSOR                     69
#define TOK_TENSOR_ID                       70
#define TOK_STENSOR_ID                      71
#define TOK_LTRUE                           72
#define TOK_LFALSE                          73
#define TOK_BOOL                            74
#define TOK_SBOOL_ID                        75
#define TOK_FACE_AREA                       76
#define TOK_FACE_EXPR                       77
#define TOK_WEIGHT_AVERAGE                  78
#define TOK_WEIGHT_SUM                      79
#define TOK_POINT_EXPR                      80
#define TOK_PSCALAR_ID                      81
#define TOK_PVECTOR_ID                      82
#define TOK_PSPH_TENSOR_ID                  83
#define TOK_PSYM_TENSOR_ID                  84
#define TOK_PTENSOR_ID                      85
#define TOK_PBOOL_ID                        86
#define TOK_POINTS                          87
#define TOK_MAG                             88
#define TOK_MAGSQR                          89
#define TOK_VECTOR                          90
#define TOK_TENSOR                          91
#define TOK_SYM_TENSOR                      92
#define TOK_SPH_TENSOR                      93
#define TOK_CMPT_X                          94
#define TOK_CMPT_Y                          95
#define TOK_CMPT_Z                          96
#define TOK_CMPT_XX                         97
#define TOK_CMPT_XY                         98
#define TOK_CMPT_XZ                         99
#define TOK_CMPT_YX                        100
#define TOK_CMPT_YY                        101
#define TOK_CMPT_YZ                        102
#define TOK_CMPT_ZX                        103
#define TOK_CMPT_ZY                        104
#define TOK_CMPT_ZZ                        105
#define TOK_CMPT_II                        106
#define TOK_TRANSPOSE                      107
#define TOK_DIAG                           108
#define TOK_POINT_TO_FACE                  109
#define TOK_FACE_TO_POINT                  110
