#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

mkdir -p constant/triSurface

cp -f \
    "$FOAM_TUTORIALS"/resources/geometry/NACA0012.obj.gz \
    constant/triSurface

runApplication blockMesh

runApplication snappyHexMesh

#------------------------------------------------------------------------------
