#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/CleanFunctions      # Tutorial clean functions
#------------------------------------------------------------------------------

(cd left && cleanCase0)
(cd right && cleanCase0)
\rm -f log.*

#------------------------------------------------------------------------------
