#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

runApplication blockMesh

runApplication topoSet

runApplication snappyHexMesh -overwrite

runApplication checkMesh

runApplication simpleFoam

#------------------------------------------------------------------------------
