#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# create mesh
runApplication blockMesh

# create ignition cells cellSet
runApplication topoSet

runApplication $(getApplication)

#------------------------------------------------------------------------------
