/*---------------------------------------------------------------------------*\
  =========                 |
  \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox
   \\    /   O peration     |
    \\  /    A nd           | Copyright (C) 2009-2009 OpenCFD Ltd.
     \\/     M anipulation  |
-------------------------------------------------------------------------------
License
    This file is part of OpenFOAM.

    OpenFOAM is free software; you can redistribute it and/or modify it
    under the terms of the GNU General Public License as published by the
    Free Software Foundation; either version 2 of the License, or (at your
    option) any later version.

    OpenFOAM is distributed in the hope that it will be useful, but WITHOUT
    ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
    FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
    for more details.

    You should have received a copy of the GNU General Public License
    along with OpenFOAM; if not, write to the Free Software Foundation,
    Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA

\*---------------------------------------------------------------------------*/

#include "pqPV3blockMeshReaderPanel.h"

// QT
#include <QGridLayout>
#include <QCheckBox>
#include <QLabel>
#include <QLayout>
#include <QString>
#include <QtDebug>

// Paraview<->QT UI
#include "pqAnimationScene.h"
#include "pqApplicationCore.h"
#include "pqPipelineRepresentation.h"
#include "pqServerManagerModel.h"

// Paraview Server Manager
#include "vtkSMDoubleVectorProperty.h"
#include "vtkSMIntVectorProperty.h"
#include "vtkSMProperty.h"
#include "vtkSMSourceProxy.h"


// * * * * * * * * * * * * * * * * Constructors  * * * * * * * * * * * * * * //

pqPV3blockMeshReaderPanel::pqPV3blockMeshReaderPanel
(
    pqProxy *proxy,
    QWidget *p
)
:
    pqAutoGeneratedObjectPanel(proxy, p),
    sourceProxy_(vtkSMSourceProxy::SafeDownCast(this->proxy()))
{
    // create first sublayout (at top of the panel)
    QGridLayout *sect1 = new QGridLayout();
    this->PanelLayout->addLayout(sect1, 0, 0, 1, -1);


    // checkbox for showing point numbers
    ShowPointNumbers_ = new QCheckBox("Show Point Numbers");
    ShowPointNumbers_->setChecked(true);

    connect
    (
        ShowPointNumbers_,
        SIGNAL(stateChanged(int)),
        this,
        SLOT(ShowPointNumbersToggled())
    );

    sect1->addWidget(ShowPointNumbers_);


    // immediate update on the Server Manager side
    vtkSMIntVectorProperty::SafeDownCast
    (
        sourceProxy_->GetProperty("UiShowPointNumbers")
    )->SetImmediateUpdate(true);

}

// * * * * * * * * * * * * * * Member Functions  * * * * * * * * * * * * * * //

void pqPV3blockMeshReaderPanel::ShowPointNumbersToggled()
{
    vtkSMIntVectorProperty::SafeDownCast
    (
        sourceProxy_->GetProperty("UiShowPointNumbers")
    )->SetElement(0, ShowPointNumbers_->isChecked());
}


// ************************************************************************* //
