package FoamXServer.CaseServer;


/**
* FoamXServer/CaseServer/IGeometryDescriptor.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from FoamX.idl
* 02 April 2007 09:53:40 o'clock BST
*/


// ---------------------------------------------------------------------
public interface IGeometryDescriptor extends IGeometryDescriptorOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface IGeometryDescriptor
