package FoamXServer.CaseServer;


/**
* FoamXServer/CaseServer/IPatchDescriptorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from FoamX.idl
* 02 April 2007 09:53:40 o'clock BST
*/


// ---------------------------------------------------------------------
public interface IPatchDescriptorOperations 
{

  //- Name of patch type (eg, "wall").
  String name ();

  //- Name of patch type (eg, "wall").
  void name (String newName);

  //- Display name (eg, "Wall").
  String displayName ();

  //- Display name (eg, "Wall").
  void displayName (String newDisplayName);

  //- Description (eg, "Solid Wall").
  String description ();

  //- Description (eg, "Solid Wall").
  void description (String newDescription);
} // interface IPatchDescriptorOperations
