#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/CleanFunctions      # Tutorial clean functions
#------------------------------------------------------------------------------

cleanCase

rm -rf 0/lagrangian 0/uniform
rm -f Ar-Ar
rm -f electrostatic
rm -f constant/idList

#------------------------------------------------------------------------------
