#!/bin/sh
cd ${0%/*} || exit 1                         # Run from this directory
. $WM_PROJECT_DIR/wmake/scripts/AllwmakeParseArguments
. $WM_PROJECT_DIR/wmake/scripts/have_fftw

#------------------------------------------------------------------------------

if have_fftw
then
    wmake $targetType
else
    echo "==> skip dnsFoam solver (no FFTW)"
fi

#------------------------------------------------------------------------------
