#!/bin/sh

m4 < constant/polyMesh/blockMeshDict.m4 > constant/polyMesh/blockMeshDict
blockMesh
cellSet
cp system/faceSetDict_rotorFaces system/faceSetDict
faceSet
cp system/faceSetDict_noBoundaryFaces system/faceSetDict
faceSet
setsToZones -noFlipMap
