#!/bin/sh
cd ${0%/*} || exit 1                        # Run from this directory
. $WM_PROJECT_DIR/bin/tools/RunFunctions    # Tutorial run functions

rm -f system/blockMeshDict
m4 system/blockMeshDict.m4 > system/blockMeshDict

runApplication blockMesh

restore0Dir

runApplication decomposePar

runParallel $(getApplication)

# Run noise tool for both point and surface

if notTest $@
then
    runParallel -s point noise -dict system/noiseDict-point

    runParallel -s surface noise -dict system/noiseDict-surface
fi


#------------------------------------------------------------------------------
