#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

rm -f system/blockMeshDict
m4 system/blockMeshDict.m4 > system/blockMeshDict

runApplication blockMesh

restore0Dir

runApplication decomposePar

runParallel $(getApplication)
