#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/CleanFunctions      # Tutorial clean functions
#------------------------------------------------------------------------------

cleanCase

rm -rf 0 postProcessing-*
rm -f *.dat *.png constant/turbulenceProperties

#------------------------------------------------------------------------------
