#!/bin/sh
cd ${0%/*} || exit 1                        # Run from this directory
. $WM_PROJECT_DIR/bin/tools/CleanFunctions  # Tutorial clean functions

cleanCase0

rm -r constant/extendedFeatureEdgeMesh constant/internalDelaunayVertices > /dev/null 2>&1
rm -f constant/triSurface/*.eMesh > /dev/null 2>&1
rm -f constant/triSurface/*_orient* > /dev/null 2>&1
rm -r constant/tetDualMesh > /dev/null 2>&1

rm -r snapToSurface?.obj tetsToSnapTo.obj > /dev/null 2>&1

rm domain coneAndSphere > /dev/null 2>&1

#------------------------------------------------------------------------------
