#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/CleanFunctions      # Tutorial clean functions
#------------------------------------------------------------------------------

cleanCase0

rm -rf constant/extendedFeatureEdgeMesh constant/internalDelaunayVertices
rm -f constant/triSurface/*.eMesh
rm -f constant/triSurface/*_orient*
rm -rf constant/tetDualMesh

rm -f snapToSurface?.obj tetsToSnapTo.obj
rm -f domain coneAndSphere

#------------------------------------------------------------------------------
