#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/CleanFunctions      # Tutorial clean functions
#------------------------------------------------------------------------------

( cd box_snappyHexMesh && cleanCase )

( cd box2D_moveDynamicMesh && cleanCase0 )

#------------------------------------------------------------------------------
