#!/bin/sh
cd ${0%/*} || exit 1                        # Run from this directory
. $WM_PROJECT_DIR/bin/tools/RunFunctions    # Tutorial run functions

# Make 3D mesh in slab of cells.
(
    cd box_snappyHexMesh || exit 1

    runApplication blockMesh
    runApplication snappyHexMesh -overwrite
    runApplication renumberMesh -overwrite
    runApplication createPatch -overwrite

)

# Make a 2D mesh by extruding a patch and solve to steady state.
(
    cd box2D_moveDynamicMesh || exit 1

    runApplication extrudeMesh
    restore0Dir
    runApplication moveDynamicMesh -checkAMI
)


#------------------------------------------------------------------------------
