#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Run a precursor channel flow to create a fully developed flow profile for the
# main case
(cd initChannel && ./Allrun)

# Run the main case
(cd fullCase && ./Allrun)


