#!/bin/sh

# create mesh
blockMesh >& log.blockMesh

# create sets - 1
setSet -batch system/sets.setSet >& log.setSet1

# create the first cyclic - lhs of porous zone
createBaffles cycLeft cycLeft -overwrite >& log.createBaffles1

# create sets - 2 (ordering changed after createBaffles)
setSet -batch system/sets.setSet >& log.setSet2

# create the second cyclic - rhs of porous zone
createBaffles cycRight cycRight -overwrite >& log.createBaffles2

# create sets - 3 (ordering changed after createBaffles)
setSet -batch system/sets.setSet >& log.setSet3

# convert sets to zones
setsToZones -noFlipMap >& log.setsToZones


