#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

./Allrun.pre

runApplication decomposePar

runParallel -s 1 $(getApplication)

runApplication reconstructPar


# restart

latestTime=$(foamListTimes -latestTime)

mv -f "$latestTime" "$latestTime".bak

rm -rf processor*

runParallel -s decompose redistributePar -decompose -latestTime

runParallel -s 2 $(getApplication)

runParallel -s reconstruct redistributePar -reconstruct -latestTime

#------------------------------------------------------------------------------
