#!/bin/sh

# Get application directory
parentDir=`dirname $PWD`
application=`basename $parentDir`

# Find and source additional functions
tutorialPath=$PWD
while [ ! -f $tutorialPath/RunFunctions ]
do
    tutorialPath="$tutorialPath/.."
done
. $tutorialPath/RunFunctions



runIdeasToFoam ()
{
    if [ -f log.ideasToFoam ] ; then
        echo "ansysToFoam already run on $PWD: remove log file to run"
    else
        echo "ansysToFoam: converting mesh $1"
        ansysToFoam $1 -scale $2 > log.ansysToFoam 2>&1
    fi
}

runIdeasToFoam flange.ans 0.001
runApplication $application
runApplication foamToFieldview
runApplication foamToEnsight
