#!/bin/sh
cd "${0%/*}" || exit    # Run from this directory
#------------------------------------------------------------------------------

# echo "cleaning ${PWD##*/}"

wclean libso multiphaseSystem

wclean libso twoPhaseSystem
wclean libso twoPhaseCompressibleTurbulenceModels

#------------------------------------------------------------------------------
