#!/bin/sh
cd ${0%/*} || exit 1                                # Run from this directory
. $WM_PROJECT_DIR/bin/tools/RunFunctions            # Tutorial run functions
#------------------------------------------------------------------------------

runApplication blockMesh
restore0Dir
cp -r 0 1.36
runApplication setAlphaField

runApplication $(getApplication)

./plotGraph

#------------------------------------------------------------------------------
