package FoamXServer.CaseBrowser;


/**
* FoamXServer/CaseBrowser/ICaseBrowserHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from FoamX.idl
* 02 April 2007 09:53:40 o'clock BST
*/


// ---------------------------------------------------------------------
abstract public class ICaseBrowserHelper
{
  private static String  _id = "IDL:FoamXServer/CaseBrowser/ICaseBrowser:1.0";

  public static void insert (org.omg.CORBA.Any a, FoamXServer.CaseBrowser.ICaseBrowser that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static FoamXServer.CaseBrowser.ICaseBrowser extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (FoamXServer.CaseBrowser.ICaseBrowserHelper.id (), "ICaseBrowser");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static FoamXServer.CaseBrowser.ICaseBrowser read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_ICaseBrowserStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, FoamXServer.CaseBrowser.ICaseBrowser value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static FoamXServer.CaseBrowser.ICaseBrowser narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof FoamXServer.CaseBrowser.ICaseBrowser)
      return (FoamXServer.CaseBrowser.ICaseBrowser)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      FoamXServer.CaseBrowser._ICaseBrowserStub stub = new FoamXServer.CaseBrowser._ICaseBrowserStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
