#!/bin/sh
cd "${0%/*}" || exit    # Run from this directory

foamCleanTutorials -self
rm -rf 0/alpha.water 0/alpha.water.gz probes wallPressure pRefProbe

#------------------------------------------------------------------------------
