#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

rm -r constant/extendedFeatureEdgeMesh constant/internalDelaunayVertices > /dev/null 2>&1
rm constant/triSurface/flange.eMesh > /dev/null 2>&1
rm flange system/cvMeshDict system/controlDict > /dev/null 2>&1

cleanCase

# ----------------------------------------------------------------- end-of-file
