#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

restore0Dir

cp -rf $FOAM_TUTORIALS/resources/dataset/atm-HargreavesWright-2007 system/.

rasModel="kEpsilon"    # Tested options="kOmegaSST","kEpsilon"

sed "s|RAS_MODEL|$rasModel|g" constant/turbulenceProperties.template > \
    constant/turbulenceProperties

runApplication blockMesh

runApplication renumberMesh -overwrite

runApplication $(getApplication)

#------------------------------------------------------------------------------
