#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

mkdir -p constant/geometry

cp -f \
    "$FOAM_TUTORIALS"/resources/geometry/curve2.vtk.gz \
    constant/geometry

runApplication blockMesh

#------------------------------------------------------------------------------
