package FoamXServer.HostBrowser;


/**
* FoamXServer/HostBrowser/IHostBrowser.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from FoamX.idl
* 02 April 2007 09:53:40 o'clock BST
*/


// ---------------------------------------------------------------------
public interface IHostBrowser extends IHostBrowserOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface IHostBrowser
