#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication blockMesh

echo "Creating channel"
for i in 1 2
do
    cp system/extrudeMeshDict.${i} system/extrudeMeshDict
    echo "Running extrudeMesh, instance" ${i}
    extrudeMesh > log.extrudeMesh.${i}
done

#------------------------------------------------------------------------------
