#!/bin/sh
cd ${0%/*} || exit 1                        # Run from this directory
. $WM_PROJECT_DIR/bin/tools/RunFunctions    # Tutorial run functions

runApplication blockMesh
runApplication topoSet
runApplication createPatch -overwrite

cp 0/ph_rgh.orig 0/ph_rgh

runApplication decomposePar -force
runParallel $(getApplication)

#------------------------------------------------------------------------------
