#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

mkdir -p constant/triSurface

cp -f \
    "$FOAM_TUTORIALS"/resources/geometry/baffle{1,3}D.stl.gz \
    constant/triSurface

restore0Dir

runApplication blockMesh

# Create 1D and 3D baffles
runApplication createBaffles -overwrite

runApplication $(getApplication)

#------------------------------------------------------------------------------
