#!/bin/sh
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application name
application=$(getApplication)

runApplication blockMesh

restore0Dir

# Create 1D and 3D baffles
runApplication createBaffles -overwrite

runApplication $application
