#!/bin/sh
cd ${0%/*} || exit 1                            # Run from this directory
. $WM_PROJECT_DIR/wmake/scripts/cmakeFunctions  # The CMake functions

# -----------------------------------------------------------------------------

echo "======================================================================"
echo "${PWD##*/} : $PWD"

unset depend

if [ -d "$VTK_DIR" ]
then
    depend="VTK_DIR=$VTK_DIR"
elif [ -d "$ParaView_DIR" ]
then
    depend="ParaView_DIR=$ParaView_DIR"
fi

# Or force use of dummy only
# unset depend

if [ "$targetType" = objects ]
then
    depend=ignore
elif [ -n "$depend" ]
then
    if command -v cmake > /dev/null 2>&1
    then
        cmakeVersioned "$depend" $PWD || {
            echo
            echo "    WARNING: incomplete build of VTK-based post-processing"
            echo
            depend="dummy"
        }
    else
        echo "==> skip runTimePostProcessing (needs cmake)"
        depend="dummy"
    fi
else
    echo "WARNING: skip runTimePostProcessing (no VTK or ParaView)"
    echo "    - ParaView  : export the 'ParaView_DIR' variable"
    echo "    - VTK       : export the 'VTK_DIR'      variable"
fi

if [ "${depend:-dummy}" = dummy ]
then
    echo "==> dummy runTimePostProcessing"
    wmakeVersioned "vtk=dummy" $PWD dummy
fi

echo "======================================================================"

# -----------------------------------------------------------------------------
