#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
[ $# -ge 1 ] && makeOption=$1 || makeOption=libso
set -x

wmake $makeOption

# ----------------------------------------------------------------- end-of-file
