#!/bin/sh
#------------------------------------------------------------------------------
# =========                 |
# \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox
#  \\    /   O peration     |
#   \\  /    A nd           | Copyright (C) 2017 OpenCFD Ltd.
#    \\/     M anipulation  |
#-------------------------------------------------------------------------------
# License
#     This file is part of OpenFOAM.
#
#     OpenFOAM is free software: you can redistribute it and/or modify it
#     under the terms of the GNU General Public License as published by
#     the Free Software Foundation, either version 3 of the License, or
#     (at your option) any later version.
#
#     OpenFOAM is distributed in the hope that it will be useful, but WITHOUT
#     ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
#     FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
#     for more details.
#
#     You should have received a copy of the GNU General Public License
#     along with OpenFOAM.  If not, see <http://www.gnu.org/licenses/>.
#
# Script
#     createGraphs
#
# Description
#     Creates .eps graph of OpenFOAM results vs analytical solution for the
#     Joule heating case
#
#------------------------------------------------------------------------------
cd ${0%/*} || exit 1    # Run from this directory

# Stop on first error
set -e

# Test if gnuplot exists on the system
command -v gnuplot >/dev/null 2>&1 || {
    echo "FOAM FATAL ERROR: gnuplot not found - skipping graph creation" 1>&2
    exit 1
}


echo "Creating graph"
OFDATA='postProcessing/sample1/solid/20000/centreLine_T_jouleHeatingSource:V_jouleHeatingSource:sigma.xy'

[ -f "$OFDATA" ] || {
    echo "FOAM FATAL ERROR: OpenFOAM results not available in $OFDATA" 1>&2
    exit 1
}

gnuplot<<EOF
set terminal postscript eps color enhanced
set output "OF_vs_ANALYTICAL.eps"
set xlabel "Length, x / [m]"
set ylabel "Temperature / [K]"
set grid
set key left top
rho = 7.837e-6
sigma = 1/rho
kappa = 200
L = 2.5
D = 0.1
H = 0.1
vol = 2.0*L*D*H
V = 1.5
R = rho*2*L/(D*H)
I = V/R
P = I*V
Q = P/vol
Ts = 500
T(x) = Q*L*L/(2*kappa)*(1-(x/L)*(x/L)) + Ts


plot \
    "$OFDATA" u 1:2 w lines title "OpenFOAM", \
    T(x) w linespoints lt 0 pt 6 pi 15 title "Analytical"
EOF


echo "End"

#------------------------------------------------------------------------------
