#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

# Generate mesh
./Allrun-pre

# Run simulation
./Allrun-simulation

#------------------------------------------------------------------------------
