#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

nProcs=$(getNumberOfProcessors)

# copy flange surface from resources folder
cp $FOAM_TUTORIALS/resources/geometry/mixerVessel.tar.gz constant/triSurface/
tar zxf constant/triSurface/mixerVessel.tar.gz -C constant/triSurface/rawSurfaces

# Run the surface preparation script
./constant/triSurface/surfaceProcess.sh > log.surfaceProcess 2>&1

runApplication surfaceBooleanFeatures \
               intersection \
               constant/triSurface/vessel.stl \
               constant/triSurface/spargerShaft.stl -perturb

mv log.surfaceBooleanFeatures log.surfaceBooleanFeatures.vessel_spargerShaft

runApplication surfaceBooleanFeatures \
               intersection \
               constant/triSurface/vessel.stl \
               constant/triSurface/shaftStatic.stl -perturb

mv log.surfaceBooleanFeatures log.surfaceBooleanFeatures.vessel_shaftStatic

runApplication surfaceBooleanFeatures \
               intersection \
               constant/triSurface/spargerShaft.stl \
               constant/triSurface/spargerInlet.stl -perturb

mv log.surfaceBooleanFeatures log.surfaceBooleanFeatures.spargerShaft_spargerInlet

runApplication surfaceBooleanFeatures \
               intersection \
               constant/triSurface/stirrer.stl \
               constant/triSurface/shaftRotating.stl -perturb

mv log.surfaceBooleanFeatures log.surfaceBooleanFeatures.stirrer_shaftRotating

runApplication surfaceFeatureExtract

runApplication blockMesh
runApplication decomposePar

runParallel foamyHexMesh $nProcs

runParallel collapseEdges $nProcs -collapseFaces -latestTime

runParallel checkMesh $nProcs -latestTime -allTopology -allGeometry


# ----------------------------------------------------------------- end-of-file
