#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

runApplication blockMesh

runApplication decomposePar -decomposeParDict system/decomposeParDict-2

runParallel -s scotch -np 5 redistributePar \
    -decomposeParDict system/decomposeParDict-5

runParallel -np 5 Test-mapDistributePolyMesh \
    -decomposeParDict system/decomposeParDict-5

# -----------------------------------------------------------------------------
