#!/bin/sh
# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase

#rm -rf system/wallFilmRegion
rm -rf constant/wallFilmRegion
rm -rf 0
cp -rf 0.org 0
rm -rf mfr*

rm -rf *.obj

