#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

# Run a precursor init case
(cd main && ./Allrun.pre)
(cd precursor && ./Allrun-parallel)

# Run the main case
(cd main && ./Allrun-parallel)

# -----------------------------------------------------------------------------
