#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/CleanFunctions      # Tutorial clean functions
#------------------------------------------------------------------------------

cleanCase

# Remove anything with '.' separator (generated fields)
rm -f 0/*.*

#------------------------------------------------------------------------------
