#!/bin/sh
cd ${0%/*} || exit 1                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions

application=Test-volField

runApplication wmake ..

runApplication blockMesh

runApplication $application

#------------------------------------------------------------------------------
