#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Parse arguments for library compilation
. $WM_PROJECT_DIR/wmake/scripts/AllwmakeParseArguments

# Source CMake functions
. $WM_PROJECT_DIR/wmake/scripts/cmakeFunctions

# -----------------------------------------------------------------------------

if [ -d "$ParaView_DIR" ]
then
    wmakeLibPv vtkPVblockMesh

    if [ "$targetType" != objects ]
    then
        cmakePv $PWD/PVblockMeshReader || {
            echo
            echo "    WARNING: incomplete build of ParaView BlockMesh plugin"
            echo
        }
    fi
fi

#------------------------------------------------------------------------------
