#define TOK_QUESTION                         1
#define TOK_COLON                            2
#define TOK_LOR                              3
#define TOK_LAND                             4
#define TOK_BIT_XOR                          5
#define TOK_BIT_AND                          6
#define TOK_EQUAL                            7
#define TOK_NOT_EQUAL                        8
#define TOK_LESS_EQ                          9
#define TOK_GREATER_EQ                      10
#define TOK_LESS                            11
#define TOK_GREATER                         12
#define TOK_PLUS                            13
#define TOK_MINUS                           14
#define TOK_TIMES                           15
#define TOK_DIVIDE                          16
#define TOK_PERCENT                         17
#define TOK_NEGATE                          18
#define TOK_NOT                             19
#define TOK_DOT                             20
#define TOK_NUMBER                          21
#define TOK_ZERO                            22
#define TOK_PI                              23
#define TOK_LPAREN                          24
#define TOK_RPAREN                          25
#define TOK_DEG_TO_RAD                      26
#define TOK_RAD_TO_DEG                      27
#define TOK_SCALAR_ID                       28
#define TOK_MIN                             29
#define TOK_COMMA                           30
#define TOK_MAX                             31
#define TOK_SUM                             32
#define TOK_AVERAGE                         33
#define TOK_EXP                             34
#define TOK_LOG                             35
#define TOK_LOG10                           36
#define TOK_SQR                             37
#define TOK_SQRT                            38
#define TOK_CBRT                            39
#define TOK_SIN                             40
#define TOK_COS                             41
#define TOK_TAN                             42
#define TOK_ASIN                            43
#define TOK_ACOS                            44
#define TOK_ATAN                            45
#define TOK_SINH                            46
#define TOK_COSH                            47
#define TOK_TANH                            48
#define TOK_POW                             49
#define TOK_ATAN2                           50
#define TOK_POS                             51
#define TOK_NEG                             52
#define TOK_POS0                            53
#define TOK_NEG0                            54
#define TOK_SIGN                            55
#define TOK_FLOOR                           56
#define TOK_CEIL                            57
#define TOK_ROUND                           58
#define TOK_HYPOT                           59
#define TOK_RAND                            60
#define TOK_VECTOR_ID                       61
#define TOK_SPH_TENSOR_ID                   62
#define TOK_SYM_TENSOR_ID                   63
#define TOK_UNIT_TENSOR                     64
#define TOK_TENSOR_ID                       65
#define TOK_LTRUE                           66
#define TOK_LFALSE                          67
#define TOK_BOOL                            68
#define TOK_BOOL_ID                         69
#define TOK_MAG                             70
#define TOK_MAGSQR                          71
#define TOK_VECTOR                          72
#define TOK_TENSOR                          73
#define TOK_SYM_TENSOR                      74
#define TOK_SPH_TENSOR                      75
#define TOK_CMPT_X                          76
#define TOK_CMPT_Y                          77
#define TOK_CMPT_Z                          78
#define TOK_CMPT_XX                         79
#define TOK_CMPT_XY                         80
#define TOK_CMPT_XZ                         81
#define TOK_CMPT_YX                         82
#define TOK_CMPT_YY                         83
#define TOK_CMPT_YZ                         84
#define TOK_CMPT_ZX                         85
#define TOK_CMPT_ZY                         86
#define TOK_CMPT_ZZ                         87
#define TOK_CMPT_II                         88
#define TOK_TRANSPOSE                       89
#define TOK_DIAG                            90
