#define TOK_LPAREN                           1
#define TOK_RPAREN                           2
#define TOK_COMMA                            3
#define TOK_QUESTION                         4
#define TOK_COLON                            5
#define TOK_LOR                              6
#define TOK_LAND                             7
#define TOK_LNOT                             8
#define TOK_BIT_OR                           9
#define TOK_BIT_XOR                         10
#define TOK_BIT_AND                         11
#define TOK_BIT_NOT                         12
#define TOK_EQUAL                           13
#define TOK_NOT_EQUAL                       14
#define TOK_LESS                            15
#define TOK_LESS_EQ                         16
#define TOK_GREATER                         17
#define TOK_GREATER_EQ                      18
#define TOK_PLUS                            19
#define TOK_MINUS                           20
#define TOK_TIMES                           21
#define TOK_DIVIDE                          22
#define TOK_PERCENT                         23
#define TOK_NEGATE                          24
#define TOK_DOT                             25
#define TOK_BOOL                            26
#define TOK_LTRUE                           27
#define TOK_LFALSE                          28
#define TOK_NUMBER                          29
#define TOK_ZERO                            30
#define TOK_IDENTIFIER                      31
#define TOK_PI                              32
#define TOK_DEG_TO_RAD                      33
#define TOK_RAD_TO_DEG                      34
#define TOK_ARG                             35
#define TOK_TIME                            36
#define TOK_DELTA_T                         37
#define TOK_SCALAR_FUNCTION_ID              38
#define TOK_VECTOR_VALUE                    39
#define TOK_VECTOR_FUNCTION_ID              40
#define TOK_SCALAR_ID                       41
#define TOK_MIN                             42
#define TOK_MAX                             43
#define TOK_SUM                             44
#define TOK_AVERAGE                         45
#define TOK_EXP                             46
#define TOK_LOG                             47
#define TOK_LOG10                           48
#define TOK_SQR                             49
#define TOK_SQRT                            50
#define TOK_CBRT                            51
#define TOK_SIN                             52
#define TOK_COS                             53
#define TOK_TAN                             54
#define TOK_ASIN                            55
#define TOK_ACOS                            56
#define TOK_ATAN                            57
#define TOK_SINH                            58
#define TOK_COSH                            59
#define TOK_TANH                            60
#define TOK_POW                             61
#define TOK_ATAN2                           62
#define TOK_POS                             63
#define TOK_NEG                             64
#define TOK_POS0                            65
#define TOK_NEG0                            66
#define TOK_SIGN                            67
#define TOK_FLOOR                           68
#define TOK_CEIL                            69
#define TOK_ROUND                           70
#define TOK_HYPOT                           71
#define TOK_RAND                            72
#define TOK_VECTOR_ID                       73
#define TOK_SPH_TENSOR_ID                   74
#define TOK_SYM_TENSOR_ID                   75
#define TOK_IDENTITY_TENSOR                 76
#define TOK_TENSOR_ID                       77
#define TOK_BOOL_ID                         78
#define TOK_MAG                             79
#define TOK_MAGSQR                          80
#define TOK_VECTOR                          81
#define TOK_TENSOR                          82
#define TOK_SYM_TENSOR                      83
#define TOK_SPH_TENSOR                      84
#define TOK_CMPT_X                          85
#define TOK_CMPT_Y                          86
#define TOK_CMPT_Z                          87
#define TOK_CMPT_XX                         88
#define TOK_CMPT_XY                         89
#define TOK_CMPT_XZ                         90
#define TOK_CMPT_YX                         91
#define TOK_CMPT_YY                         92
#define TOK_CMPT_YZ                         93
#define TOK_CMPT_ZX                         94
#define TOK_CMPT_ZY                         95
#define TOK_CMPT_ZZ                         96
#define TOK_CMPT_II                         97
#define TOK_TRANSPOSE                       98
#define TOK_DIAG                            99
