#ifndef __pqPV3FoamReaderPanel_h
#define __pqPV3FoamReaderPanel_h

#include "pqAutoGeneratedObjectPanel.h"
#include <QLabel>
#include <QLayout>

//
// Custom panel for PV3FoamReader source.
//
class pqPV3FoamReaderPanel
:
    public pqAutoGeneratedObjectPanel
{
    Q_OBJECT;
    typedef pqAutoGeneratedObjectPanel Superclass;

public:
    pqPV3FoamReaderPanel(pqProxy *proxy, QWidget *p)
    :
        pqAutoGeneratedObjectPanel(proxy, p)
    {
        this->layout()->addWidget
        (
            new QLabel("Plugin for reading OpenFOAM meshes/results", this)
        );
    }

    //virtual ~pqPV3FoamReaderPanel();

protected:
};

#endif //__pqPV3FoamReaderPanel_h
