all: qmake
	@eval `grep export qmake.vars | awk '{ $$1=""; $$2=""; print; }'`; \
	if [ x$$MK_BUILDNAME = xwindows-x86 ]; then \
	  MAKE="nmake -nologo"; \
	  MAKEFLAGS=; \
	else \
	  MAKE=$(MAKE); \
	fi; \
	$${MAKE} -f Makefile.$(PROJECT); \
	if [ -x ./run.test ]; then \
	  ./run.test "$${TEST}" "$${test}" "$(PATHTOSRC)"; \
	else \
	  exit 0; \
	fi

qmake:
	$(PATHTOSRC)/config/runqmake $(PATHTOSRC) \
	  -o Makefile.$(PROJECT) $(PROJECT).pro 2>&1 | tee qmake.vars



test: tqmake
	@eval `grep export qmake.vars | awk '{ $$1=""; $$2=""; print; }'`; \
	if [ x$$MK_BUILDNAME = xwindows-x86 ]; then \
	  MAKE="nmake -nologo"; \
	  MAKEFLAGS=; \
	else \
	  MAKE=$(MAKE); \
	fi; \
	$${MAKE} -f Makefile.$(PROJECT); \
	TEST=1; export TEST; \
	if [ -x ./run.test ]; then \
	  ./run.test "$${TEST}" "$${test}" "$(PATHTOSRC)"; \
	else \
	  exit 0; \
	fi

tqmake:
	TEST=1; export TEST; \
	$(PATHTOSRC)/config/runqmake $(PATHTOSRC) \
	  -o Makefile.$(PROJECT) $(PROJECT).pro 2>&1 | tee qmake.vars



clean: qmake
	@eval `grep export qmake.vars | awk '{ $$1=""; $$2=""; print; }'`; \
	if [ x$$MK_BUILDNAME = xwindows-x86 ]; then \
	  MAKE="nmake -nologo"; \
	  MAKEFLAGS=; \
	else \
	  MAKE=$(MAKE); \
	fi; \
	$${MAKE} -f Makefile.$(PROJECT) distclean

tags:
	etags *.h *.cpp

copy:
