#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x

makeOption=libso
[ $# -ge 1 ] && makeOption=$1

wmake $makeOption turbulenceModel
wmake $makeOption RAS
wmake $makeOption LES

# ----------------------------------------------------------------- end-of-file
