#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

restore0Dir

runApplication blockMesh

runApplication decomposePar

runParallel $(getApplication)

runApplication reconstructPar

runApplication -s sigma \
    postProcess -func "components(sigma)" -noZero

runApplication -s singleGraph \
    postProcess -func singleGraph -noZero

#------------------------------------------------------------------------------
