#!/bin/sh
#------------------------------------------------------------------------------
# =========                 |
# \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox
#  \\    /   O peration     |
#   \\  /    A nd           | Copyright (C) 1991-2009 OpenCFD Ltd.
#    \\/     M anipulation  |
#-------------------------------------------------------------------------------
# License
#     This file is part of OpenFOAM.
#
#     OpenFOAM is free software; you can redistribute it and/or modify it
#     under the terms of the GNU General Public License as published by the
#     Free Software Foundation; either version 2 of the License, or (at your
#     option) any later version.
#
#     OpenFOAM is distributed in the hope that it will be useful, but WITHOUT
#     ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
#     FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
#     for more details.
#
#     You should have received a copy of the GNU General Public License
#     along with OpenFOAM; if not, write to the Free Software Foundation,
#     Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
#
# Script
#     wmakeLnIncludeAll
#
# Description
#     Find directories containing an lnInclude/ directory and execute
#     'wmakeLnInclude -f' for each one
#
#------------------------------------------------------------------------------
usage() {
    while [ "$#" -ge 1 ]; do echo "$1"; shift; done
    cat<<USAGE

usage: ${0##*/} [-make] [dir1 .. dirN]

    Find directories containing an lnInclude/ directory and execute
    'wmakeLnInclude -f' for each one

Note
    Use the '-make' option to search for Make/ instead of lnInclude/

USAGE
    exit 1
}

#------------------------------------------------------------------------------
findName=lnInclude

# simple parse options
while [ "$#" -gt 0 ]
do
    case "$1" in
    -h | -help)   # provide immediate help
        usage
        ;;
    -make)
        shift
        findName=Make
        ;;
    -*)
        usage "unknown option: '$*'"
        ;;
    *)
        break
        ;;
    esac
done


# default to searching from pwd
[ "$#" -gt 0 ] || set -- .

for checkDir
do
    if [ -d $checkDir ]
    then
        echo "searching: $checkDir for '$findName' directories"
        echo "---------"
    else
        echo "skipping non-dir: $checkDir"
        echo "----------------"
        continue
    fi

    find $checkDir -depth -type d -name $findName -print | while read dir
    do
        dir=${dir%/$findName}    # trim findName from the end
        if [ -d "$dir" ]
        then
            wmakeLnInclude -f $dir
        fi
    done
done

#------------------------------------------------------------------------------
