#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

keepCases="cavity cavityGrade cavityClipped elbow"
loseCases="cavityFine cavityHighRe"

for caseName in $keepCases
do
(
    cd $caseName || exit

    foamCleanTutorials

    if [ "$caseName" = elbow ]
    then
        rm -rf fluentInterface
    fi
    if [ "$caseName" = cavityClipped ]
    then
        rm -rf 0
    fi
)
done

for caseName in $loseCases
do
    removeCase $caseName
done


(cd elbow && ./Allclean)

# ----------------------------------------------------------------- end-of-file
