#!/bin/sh
cd ${0%/*} || exit 1                        # Run from this directory
. $WM_PROJECT_DIR/bin/tools/RunFunctions    # Tutorial run functions

runApplication surfaceFeatureExtract

runApplication blockMesh
runApplication snappyHexMesh -overwrite

rm -rf 0

runApplication createBaffles -overwrite
runApplication mergeOrSplitBaffles -split -overwrite

restore0Dir

runApplication $(getApplication)

#------------------------------------------------------------------------------
