#!/bin/sh
cd ${0%/*} || exit 1                        # Run from this directory
. $WM_PROJECT_DIR/bin/tools/CleanFunctions  # Tutorial clean functions

cleanCase0

rm -rf VTK
rm -rf constant/cellToRegion
rm -rf constant/*/polyMesh  # region meshes

rm -f constant/bottomAir/F
rm -f constant/bottomAir/constructMap*
rm -f constant/bottomAir/finalAgglom
rm -f constant/bottomAir/globalFaceFaces
rm -f constant/bottomAir/subMap
rm -f constant/bottomAir/visibleFaceFaces
rm -f constant/bottomAir/mapDist

rm -f constant/topAir/F
rm -f constant/topAir/constructMap*
rm -f constant/topAir/finalAgglom
rm -f constant/topAir/globalFaceFaces
rm -f constant/topAir/subMap
rm -f constant/topAir/visibleFaceFaces
rm -f constant/topAir/mapDist

#------------------------------------------------------------------------------
