#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Setup case
./Allrun.pre

#-- Run in parallel

# Decompose
runApplication decomposePar -allRegions

# Agglomerate patch faces
for i in bottomAir topAir
do
    runParallel -s $i \
        faceAgglomerate -region $i -dict constant/viewFactorsDict
done

# Generate view factors
for i in bottomAir topAir
do
    runParallel -s $i \
        viewFactorsGen -region $i
done

# Run
runParallel $(getApplication)

# Reconstruct
runApplication reconstructPar -allRegions

echo
echo "Creating files for paraview post-processing"
echo
paraFoam -touchAll

#------------------------------------------------------------------------------
