#!/bin/sh
cd ${0%/*} || exit 1                        # Run from this directory
. $WM_PROJECT_DIR/bin/tools/RunFunctions    # Tutorial run functions

# Setup case
./Allrun.pre

#-- Run in parallel

# Decompose
runApplication decomposePar -allRegions

# Agglomerate patch faces
for region in bottomAir topAir
do
    runParallel -s $region \
        faceAgglomerate -region $region -dict constant/viewFactorsDict
done

# Generate view factors
for region in bottomAir topAir
do
    runParallel -s $region \
        viewFactorsGen -region $region
done

# Run
runParallel $(getApplication)

# Reconstruct
runApplication reconstructPar -allRegions

echo
echo "Use paraFoam -touch-all to create files for paraview post-processing"
echo

#------------------------------------------------------------------------------
