#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
# No AllwmakeParseArguments [infinite loop via Allwmake]
. ${WM_PROJECT_DIR:?}/wmake/scripts/wmake.wmake-args
. ${WM_PROJECT_DIR:?}/wmake/scripts/wmakeFunctions  # Require wmake functions

#------------------------------------------------------------------------------
# Environment
#   - FOAM_MPI_LIBBIN (optional: defaults to FOAM_LIBBIN/FOAM_MPI)

wmakeLibMpi mpi

#------------------------------------------------------------------------------
