#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Clean an mpi-versioned library
wcleanMpiLib()
{
    case "$WM_MPLIB" in (*MPI*)
    (
        WM_OPTIONS="$WM_OPTIONS$WM_MPLIB"
        for libName
        do
            wclean $libName
        done
    )
    ;;
    esac
}


wclean dummy
wcleanMpiLib mpi

#------------------------------------------------------------------------------
