#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
makeType=${1:-libso}
set -x

wmake $makeType dummy

case "$WM_MPLIB" in
*MPI*)
    set +x
    echo
    echo "Note: ignore spurious warnings about missing mpicxx.h headers"
    echo
    set -x
    # force compilation into qualified directory
    WM_OPTIONS=${WM_OPTIONS}$WM_MPLIB  wmake $makeType mpi
    ;;

#GAMMA)
#    wmake $makeType gamma
#    ;;
esac


# ----------------------------------------------------------------- end-of-file
