#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x

wmake libso dummy

case "$WM_MPLIB" in
GAMMA)
   wmake libso gamma
   ;;

LAM | *MPI* )
   export WM_OPTIONS=${WM_OPTIONS}$WM_MPLIB
   set +x
   echo
   echo "Note: ignore spurious warnings about missing mpicxx.h headers"
   set -x
   wmake libso mpi
   ;;
esac

# ----------------------------------------------------------------- end-of-file
