#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

# Generate mesh if required
[ -d constant/polyMesh ] || ./Allrun.pre

restore0Dir

runApplication decomposePar

runParallel $(getApplication)

vibroAcousticCase="../main"
dataDir="postProcessing/surfaces/window"

mkdir -p "$vibroAcousticCase"/constant/boundaryData
cp -rf "$dataDir" "$vibroAcousticCase"/constant/boundaryData/window

# -----------------------------------------------------------------------------
