#!/bin/sh
cd "${0%/*}" || exit    # Run from this directory
#------------------------------------------------------------------------------

m4 system/blockMeshDict.m4 > system/blockMeshDict
blockMesh > log.blockMesh 2>&1

#------------------------------------------------------------------------------
