#!/bin/sh
cd "${0%/*}" || exit                        # Run from this directory

#------------------------------------------------------------------------------
touch=true

case "$1" in
-check)
    if wmake -build-info -check
    then
        unset touch
    fi
    ;;
esac

if [ -n "$touch" ]
then
    # Triggers update of version info
    wrmo global/foamConfig.Cver 2>/dev/null
fi

exit 0 # clean exit

#------------------------------------------------------------------------------
