#!/bin/sh

currDir=`pwd`
application=`basename $currDir`
case="boxTurb16"

tutorialPath=`dirname $0`/..
. $tutorialPath/RunFunctions

runApplication blockMesh $case
runApplication boxTurb $case
runApplication $application $case
runApplication enstrophy $case
