#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

./makeMesh

restore0Dir
runApplication setFields

#runApplication $(getApplication)

#runApplication decomposePar
#runParallel $(getApplication)
#runApplication reconstructPar

#------------------------------------------------------------------------------
