#!/bin/sh
set -x

if [ "$ParaView_VERSION" = "3" -a "$ParaView_DIR" -a -r $ParaView_DIR ] ; then
    wmake libso vtkPV3Foam
    (cd PV3FoamReader; mkdir -p Make/$WM_OPTIONS > /dev/null 2>&1; cd Make/$WM_OPTIONS; cmake ../..; make)
fi
