#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x

rm -rf PV3FoamBlockMeshReader/Make
wclean libso vtkPV3FoamBlockMesh

# ----------------------------------------------------------------- end-of-file
