#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication blockMesh
runApplication snappyHexMesh -overwrite
runApplication transformPoints -scale '(2 1 1)'
cp 0/alpha1.org 0/alpha1
runApplication setFields
runApplication LTSInterFoam
