#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication blockMesh
runApplication snappyHexMesh -overwrite
transformPoints -scale '(2 1 1)'
cp 0/alpha1.org 0/alpha1
runApplication setFields
runApplication `getApplication`

# ----------------------------------------------------------------- end-of-file
