#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/CleanFunctions      # Tutorial clean functions
#------------------------------------------------------------------------------

( cd blob && ./Allclean )
( cd simpleShapes && ./Allclean )

if notTest "$@"
then
    ( cd flange && ./Allclean )
    ( cd mixerVessel && ./Allclean )
fi

#------------------------------------------------------------------------------
