#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

rm *.obj
rm -r constant/extendedFeatureEdgeMesh
rm constant/triSurface/boundaryAndFaceZones.eMesh
rm constant/polyMesh/boundary

cleanCase

# ----------------------------------------------------------------- end-of-file
