#!/bin/sh

currDir=`pwd`
application=`basename $currDir`
cases="pitzDaily pitzDailyDirectMapped"

tutorialPath=`dirname $0`/..
. $tutorialPath/RunFunctions

for case in $cases
do
    runApplication blockMesh $case

    if [ "$case" = "pitzDailyDirectMapped" ] 
    then
        runApplication changeDictionary $case 
    fi

    runApplication $application $case
done
