#!/bin/sh
cd ${0%/*} || exit 1                        # Run from this directory
. $WM_PROJECT_DIR/bin/tools/RunFunctions    # Tutorial run functions

restore0Dir

runApplication blockMesh
runApplication -s 1 topoSet
runApplication -s 1 refineMesh -overwrite
runApplication -s 2 topoSet -dict system/topoSetDict2
runApplication -s 2 refineMesh -overwrite

runApplication setAlphaField

runApplication $(getApplication)

#------------------------------------------------------------------------------
