#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

restore0Dir

runApplication blockMesh

runApplication -s cRefine \
    topoSet -dict system/cRefine.topoSetDict

runApplication refineMesh -overwrite -dict system/refineMeshDict

runApplication -s f \
    topoSet -dict system/f.topoSetDict

# create the pyrolysis region.
runApplication extrudeToRegionMesh -overwrite

runApplication -s fBurner \
    topoSet -dict system/fBurner.topoSetDict

runApplication createPatch -overwrite

runApplication -s master \
    decomposePar -force

runApplication -s panelRegion \
    decomposePar -region panelRegion

runApplication -s fields \
    decomposePar -fields

runParallel $(getApplication)

#------------------------------------------------------------------------------
