#define TOK_QUESTION                         1
#define TOK_COLON                            2
#define TOK_LOR                              3
#define TOK_LAND                             4
#define TOK_BIT_XOR                          5
#define TOK_BIT_AND                          6
#define TOK_EQUAL                            7
#define TOK_NOT_EQUAL                        8
#define TOK_LESS_EQ                          9
#define TOK_GREATER_EQ                      10
#define TOK_LESS                            11
#define TOK_GREATER                         12
#define TOK_PLUS                            13
#define TOK_MINUS                           14
#define TOK_TIMES                           15
#define TOK_DIVIDE                          16
#define TOK_PERCENT                         17
#define TOK_NEGATE                          18
#define TOK_NOT                             19
#define TOK_DOT                             20
#define TOK_NUMBER                          21
#define TOK_ZERO                            22
#define TOK_PI                              23
#define TOK_LPAREN                          24
#define TOK_RPAREN                          25
#define TOK_DEG_TO_RAD                      26
#define TOK_RAD_TO_DEG                      27
#define TOK_TIME                            28
#define TOK_SCALAR_ID                       29
#define TOK_MIN                             30
#define TOK_COMMA                           31
#define TOK_MAX                             32
#define TOK_SUM                             33
#define TOK_AVERAGE                         34
#define TOK_EXP                             35
#define TOK_LOG                             36
#define TOK_LOG10                           37
#define TOK_SQR                             38
#define TOK_SQRT                            39
#define TOK_CBRT                            40
#define TOK_SIN                             41
#define TOK_COS                             42
#define TOK_TAN                             43
#define TOK_ASIN                            44
#define TOK_ACOS                            45
#define TOK_ATAN                            46
#define TOK_SINH                            47
#define TOK_COSH                            48
#define TOK_TANH                            49
#define TOK_POW                             50
#define TOK_ATAN2                           51
#define TOK_POS                             52
#define TOK_NEG                             53
#define TOK_POS0                            54
#define TOK_NEG0                            55
#define TOK_SIGN                            56
#define TOK_FLOOR                           57
#define TOK_CEIL                            58
#define TOK_ROUND                           59
#define TOK_HYPOT                           60
#define TOK_RAND                            61
#define TOK_VECTOR_ID                       62
#define TOK_SPH_TENSOR_ID                   63
#define TOK_SYM_TENSOR_ID                   64
#define TOK_UNIT_TENSOR                     65
#define TOK_TENSOR_ID                       66
#define TOK_LTRUE                           67
#define TOK_LFALSE                          68
#define TOK_BOOL                            69
#define TOK_CSET                            70
#define TOK_IDENTIFIER                      71
#define TOK_CZONE                           72
#define TOK_CELL_VOLUME                     73
#define TOK_WEIGHT_AVERAGE                  74
#define TOK_WEIGHT_SUM                      75
#define TOK_FACE_EXPR                       76
#define TOK_SSCALAR_ID                      77
#define TOK_SVECTOR_ID                      78
#define TOK_SSPH_TENSOR_ID                  79
#define TOK_SSYM_TENSOR_ID                  80
#define TOK_STENSOR_ID                      81
#define TOK_FSET                            82
#define TOK_FZONE                           83
#define TOK_FACE_AREA                       84
#define TOK_FACE_CENTRE                     85
#define TOK_POINT_EXPR                      86
#define TOK_PSCALAR_ID                      87
#define TOK_PVECTOR_ID                      88
#define TOK_PSPH_TENSOR_ID                  89
#define TOK_PSYM_TENSOR_ID                  90
#define TOK_PTENSOR_ID                      91
#define TOK_PSET                            92
#define TOK_PZONE                           93
#define TOK_POINTS                          94
#define TOK_MAG                             95
#define TOK_MAGSQR                          96
#define TOK_VECTOR                          97
#define TOK_TENSOR                          98
#define TOK_SYM_TENSOR                      99
#define TOK_SPH_TENSOR                     100
#define TOK_CMPT_X                         101
#define TOK_CMPT_Y                         102
#define TOK_CMPT_Z                         103
#define TOK_CMPT_XX                        104
#define TOK_CMPT_XY                        105
#define TOK_CMPT_XZ                        106
#define TOK_CMPT_YX                        107
#define TOK_CMPT_YY                        108
#define TOK_CMPT_YZ                        109
#define TOK_CMPT_ZX                        110
#define TOK_CMPT_ZY                        111
#define TOK_CMPT_ZZ                        112
#define TOK_CMPT_II                        113
#define TOK_TRANSPOSE                      114
#define TOK_DIAG                           115
#define TOK_POINT_TO_CELL                  116
#define TOK_RECONSTRUCT                    117
#define TOK_CELL_TO_FACE                   118
#define TOK_CELL_TO_POINT                  119
