#define TOK_QUESTION                         1
#define TOK_COLON                            2
#define TOK_LOR                              3
#define TOK_LAND                             4
#define TOK_BIT_XOR                          5
#define TOK_BIT_AND                          6
#define TOK_EQUAL                            7
#define TOK_NOT_EQUAL                        8
#define TOK_LESS_EQ                          9
#define TOK_GREATER_EQ                      10
#define TOK_LESS                            11
#define TOK_GREATER                         12
#define TOK_PLUS                            13
#define TOK_MINUS                           14
#define TOK_TIMES                           15
#define TOK_DIVIDE                          16
#define TOK_PERCENT                         17
#define TOK_NEGATE                          18
#define TOK_NOT                             19
#define TOK_DOT                             20
#define TOK_NUMBER                          21
#define TOK_ZERO                            22
#define TOK_PI                              23
#define TOK_LPAREN                          24
#define TOK_RPAREN                          25
#define TOK_DEG_TO_RAD                      26
#define TOK_RAD_TO_DEG                      27
#define TOK_ARG                             28
#define TOK_TIME                            29
#define TOK_DELTA_T                         30
#define TOK_SCALAR_ID                       31
#define TOK_MIN                             32
#define TOK_COMMA                           33
#define TOK_MAX                             34
#define TOK_SUM                             35
#define TOK_AVERAGE                         36
#define TOK_EXP                             37
#define TOK_LOG                             38
#define TOK_LOG10                           39
#define TOK_SQR                             40
#define TOK_SQRT                            41
#define TOK_CBRT                            42
#define TOK_SIN                             43
#define TOK_COS                             44
#define TOK_TAN                             45
#define TOK_ASIN                            46
#define TOK_ACOS                            47
#define TOK_ATAN                            48
#define TOK_SINH                            49
#define TOK_COSH                            50
#define TOK_TANH                            51
#define TOK_POW                             52
#define TOK_ATAN2                           53
#define TOK_POS                             54
#define TOK_NEG                             55
#define TOK_POS0                            56
#define TOK_NEG0                            57
#define TOK_SIGN                            58
#define TOK_FLOOR                           59
#define TOK_CEIL                            60
#define TOK_ROUND                           61
#define TOK_HYPOT                           62
#define TOK_RAND                            63
#define TOK_VECTOR_ID                       64
#define TOK_SPH_TENSOR_ID                   65
#define TOK_SYM_TENSOR_ID                   66
#define TOK_IDENTITY_TENSOR                 67
#define TOK_TENSOR_ID                       68
#define TOK_LTRUE                           69
#define TOK_LFALSE                          70
#define TOK_BOOL                            71
#define TOK_CELL_SET                        72
#define TOK_IDENTIFIER                      73
#define TOK_CELL_ZONE                       74
#define TOK_CELL_VOLUME                     75
#define TOK_WEIGHT_AVERAGE                  76
#define TOK_WEIGHT_SUM                      77
#define TOK_FACE_EXPR                       78
#define TOK_SSCALAR_ID                      79
#define TOK_SVECTOR_ID                      80
#define TOK_SSPH_TENSOR_ID                  81
#define TOK_SSYM_TENSOR_ID                  82
#define TOK_STENSOR_ID                      83
#define TOK_FACE_SET                        84
#define TOK_FACE_ZONE                       85
#define TOK_FACE_AREA                       86
#define TOK_FACE_CENTRE                     87
#define TOK_POINT_EXPR                      88
#define TOK_PSCALAR_ID                      89
#define TOK_PVECTOR_ID                      90
#define TOK_PSPH_TENSOR_ID                  91
#define TOK_PSYM_TENSOR_ID                  92
#define TOK_PTENSOR_ID                      93
#define TOK_POINT_SET                       94
#define TOK_POINT_ZONE                      95
#define TOK_POINTS                          96
#define TOK_MAG                             97
#define TOK_MAGSQR                          98
#define TOK_VECTOR                          99
#define TOK_TENSOR                         100
#define TOK_SYM_TENSOR                     101
#define TOK_SPH_TENSOR                     102
#define TOK_CMPT_X                         103
#define TOK_CMPT_Y                         104
#define TOK_CMPT_Z                         105
#define TOK_CMPT_XX                        106
#define TOK_CMPT_XY                        107
#define TOK_CMPT_XZ                        108
#define TOK_CMPT_YX                        109
#define TOK_CMPT_YY                        110
#define TOK_CMPT_YZ                        111
#define TOK_CMPT_ZX                        112
#define TOK_CMPT_ZY                        113
#define TOK_CMPT_ZZ                        114
#define TOK_CMPT_II                        115
#define TOK_TRANSPOSE                      116
#define TOK_DIAG                           117
#define TOK_POINT_TO_CELL                  118
#define TOK_RECONSTRUCT                    119
#define TOK_CELL_TO_FACE                   120
#define TOK_CELL_TO_POINT                  121
