package FoamXServer;


/**
* FoamXServer/ApplicationDescriptorListHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from FoamX.idl
* 02 April 2007 09:53:40 o'clock BST
*/

public final class ApplicationDescriptorListHolder implements org.omg.CORBA.portable.Streamable
{
  public FoamXServer.ApplicationDescriptor value[] = null;

  public ApplicationDescriptorListHolder ()
  {
  }

  public ApplicationDescriptorListHolder (FoamXServer.ApplicationDescriptor[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = FoamXServer.ApplicationDescriptorListHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    FoamXServer.ApplicationDescriptorListHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return FoamXServer.ApplicationDescriptorListHelper.type ();
  }

}
