package FoamXServer;


/**
* FoamXServer/FoamXErrorHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from FoamX.idl
* 02 April 2007 09:53:40 o'clock BST
*/

abstract public class FoamXErrorHelper
{
  private static String  _id = "IDL:FoamXServer/FoamXError:1.0";

  public static void insert (org.omg.CORBA.Any a, FoamXServer.FoamXError that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static FoamXServer.FoamXError extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [5];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = FoamXServer.ErrorCodeHelper.type ();
          _members0[0] = new org.omg.CORBA.StructMember (
            "errorCode",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[1] = new org.omg.CORBA.StructMember (
            "errorMessage",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[2] = new org.omg.CORBA.StructMember (
            "methodName",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[3] = new org.omg.CORBA.StructMember (
            "fileName",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[4] = new org.omg.CORBA.StructMember (
            "lineNo",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_exception_tc (FoamXServer.FoamXErrorHelper.id (), "FoamXError", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static FoamXServer.FoamXError read (org.omg.CORBA.portable.InputStream istream)
  {
    FoamXServer.FoamXError value = new FoamXServer.FoamXError ();
    // read and discard the repository ID
    istream.read_string ();
    value.errorCode = FoamXServer.ErrorCodeHelper.read (istream);
    value.errorMessage = istream.read_string ();
    value.methodName = istream.read_string ();
    value.fileName = istream.read_string ();
    value.lineNo = istream.read_long ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, FoamXServer.FoamXError value)
  {
    // write the repository ID
    ostream.write_string (id ());
    FoamXServer.ErrorCodeHelper.write (ostream, value.errorCode);
    ostream.write_string (value.errorMessage);
    ostream.write_string (value.methodName);
    ostream.write_string (value.fileName);
    ostream.write_long (value.lineNo);
  }

}
