package FoamXServer;

/**
* FoamXServer/ITypeDescriptorHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from FoamX.idl
* 02 April 2007 09:53:40 o'clock BST
*/


// -------------------------------------------------------------------------
public final class ITypeDescriptorHolder implements org.omg.CORBA.portable.Streamable
{
  public FoamXServer.ITypeDescriptor value = null;

  public ITypeDescriptorHolder ()
  {
  }

  public ITypeDescriptorHolder (FoamXServer.ITypeDescriptor initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = FoamXServer.ITypeDescriptorHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    FoamXServer.ITypeDescriptorHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return FoamXServer.ITypeDescriptorHelper.type ();
  }

}
