package FoamXServer;


/**
* FoamXServer/JobDescriptor.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from FoamX.idl
* 02 April 2007 09:53:40 o'clock BST
*/


// Job descriptor structure.
public final class JobDescriptor implements org.omg.CORBA.portable.IDLEntity
{
  public FoamXServer.JobID jobID = null;

  // Job ID.
  public int ppid = (int)0;

  // Parent pid.
  public int pgid = (int)0;

  // Group pid.
  public String startDate = null;

  // Start date.
  public String startTime = null;

  // Start time.
  public String userName = null;

  // Username.
  public String foamVersion = null;

  // Software version.
  public String code = null;

  // Code.
  public String argList = null;

  // Argument list.
  public String currentDir = null;

  // Current working directory.
  public String rootDir = null;

  // Case root.
  public String caseName = null;

  // Case name.
  public int nProcs = (int)0;

  // Number of processes.
  public FoamXServer.JobID slaves[] = null;

  // slave JobIDs
  public int nCountedProcs = (int)0;

  // Number of licences taken up.
  public double cpuTime = (double)0;

  // Used cpuTime.
  public String endDate = null;

  // End date.
  public String endTime = null;

  // End time.
  public FoamXServer.JobStatus status = null;

  public JobDescriptor ()
  {
  } // ctor

  public JobDescriptor (FoamXServer.JobID _jobID, int _ppid, int _pgid, String _startDate, String _startTime, String _userName, String _foamVersion, String _code, String _argList, String _currentDir, String _rootDir, String _caseName, int _nProcs, FoamXServer.JobID[] _slaves, int _nCountedProcs, double _cpuTime, String _endDate, String _endTime, FoamXServer.JobStatus _status)
  {
    jobID = _jobID;
    ppid = _ppid;
    pgid = _pgid;
    startDate = _startDate;
    startTime = _startTime;
    userName = _userName;
    foamVersion = _foamVersion;
    code = _code;
    argList = _argList;
    currentDir = _currentDir;
    rootDir = _rootDir;
    caseName = _caseName;
    nProcs = _nProcs;
    slaves = _slaves;
    nCountedProcs = _nCountedProcs;
    cpuTime = _cpuTime;
    endDate = _endDate;
    endTime = _endTime;
    status = _status;
  } // ctor

} // class JobDescriptor
