package FoamXServer;

/**
* FoamXServer/ValidationErrorHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from FoamX.idl
* 02 April 2007 09:53:40 o'clock BST
*/

public final class ValidationErrorHolder implements org.omg.CORBA.portable.Streamable
{
  public FoamXServer.ValidationError value = null;

  public ValidationErrorHolder ()
  {
  }

  public ValidationErrorHolder (FoamXServer.ValidationError initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = FoamXServer.ValidationErrorHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    FoamXServer.ValidationErrorHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return FoamXServer.ValidationErrorHelper.type ();
  }

}
