#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication blockMesh
runApplication cvMesh
#runApplication collapseEdges 1e-10 180 -overwrite
runApplication snappyHexMesh -overwrite
runApplication checkMesh -constant -allGeometry -allTopology

# ----------------------------------------------------------------- end-of-file
