#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions


runApplication blockMesh

# Create faceZones for baffles and fan
runApplication topoSet

restore0Dir

# Create wall and cyclic baffles and the fields on them
runApplication createBaffles -overwrite

runApplication $(getApplication)

# -----------------------------------------------------------------------------
