#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

makeOption=libso
[ $# -ge 1 ] && makeOption=$1

# get SCOTCH_VERSION, SCOTCH_ARCH_PATH
settings=`$WM_PROJECT_DIR/bin/foamEtcFile apps/scotch/bashrc`
if [ -f "$settings" ]
then
    . $settings
    echo "using SCOTCH_ARCH_PATH=$SCOTCH_ARCH_PATH"
else
    echo
    echo "Error: no apps/scotch/bashrc settings"
    echo
fi
set -x

wmakeLnInclude decompositionMethods

wmake $makeOption scotchDecomp

if [ -d "$FOAM_LIBBIN/$FOAM_MPI" ]
then
(
    WM_OPTIONS=${WM_OPTIONS}$WM_MPLIB
    wmake $makeOption ptscotchDecomp
)
fi

wmake $makeOption decompositionMethods


# ----------------------------------------------------------------- end-of-file
