#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

wmakeLnInclude -u decompositionMethods
wmakeLnInclude -u kahipDecomp
wmakeLnInclude -u metisDecomp
wmakeLnInclude -u scotchDecomp
wmakeLnInclude -u ptscotchDecomp

#------------------------------------------------------------------------------
