#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x

SCOTCH_VERSION=scotch_5.1.10b
SCOTCH_ARCH_PATH=$WM_THIRD_PARTY_DIR/platforms/$WM_ARCH$WM_COMPILER/$SCOTCH_VERSION
export SCOTCH_ARCH_PATH

wmakeLnInclude decompositionMethods

wmake libso scotchDecomp
wmake libso metisDecomp

if [ -d "$FOAM_MPI_LIBBIN" ]
then
(
    WM_OPTIONS=${WM_OPTIONS}$WM_MPLIB
    wmake libso ptscotchDecomp
)
fi

wmake libso decompositionMethods


# ----------------------------------------------------------------- end-of-file
