#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase
rm -rf 0

rm system/cellSetDict > /dev/null 2>&1

#------------------------------------------------------------------------------
