#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/CleanFunctions      # Tutorial clean functions
#------------------------------------------------------------------------------

(cd fluid && foamCleanTutorials)
(cd solid && foamCleanTutorials)
rm -rf logs
rm -f log.*

#------------------------------------------------------------------------------
