#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application name from directory
application="pisoFoam"

rasCases="cavity"
lesCases="pitzDaily pitzDailyDirectMapped"

computeCase()
{
    if [ -f Allrun ] ; then
        ./Allrun
    else
        runApplication blockMesh
        runApplication $application
    fi
}

cd ras
for case in $rasCases
do
    cd $case
    computeCase
    cd ..
done
cd ..

cd les
for case in $lesCases
do
    cd $case
    computeCase
    cd ..
done
cd ..
