include ../Makefile.in

default:
	(cd IMParMetis-2.0 ; $(make) )
	(cd ParLib ; $(make) ) 
	(cd Programs ; $(make) ) 

clean:
	(cd IMParMetis-2.0 ; $(make) clean )
	(cd ParLib ; $(make) clean )
	(cd Programs ; $(make) clean )

realclean:
	(cd IMParMetis-2.0 ; $(make) realclean )
	(cd ParLib ; $(make) realclean )
	(cd Programs ; $(make) realclean )
