#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x

wmake libo postCalc
wmake libso forces
wmake libso fieldAverage
wmake libso foamCalcFunctions
wmake libso minMaxFields

# ----------------------------------------------------------------- end-of-file
