#!/bin/sh

currDir=`pwd`
application=`basename $currDir`
case="channel395"

tutorialPath=`dirname $0`/..
. $tutorialPath/RunFunctions

runApplication blockMesh $case
runApplication $application $case
runApplication postChannel $case

