#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

./Allrun.pre

runApplication -s primaryRegion  decomposePar
runApplication -s wallFilmRegion decomposePar -region wallFilmRegion


runParallel $(getApplication)

runApplication -s wallFilmRegion reconstructPar -region wallFilmRegion
runApplication -s primaryRegion  reconstructPar

#------------------------------------------------------------------------------
