#!/bin/sh
cd ${0%/*} || exit 1                        # Run from this directory
. $WM_PROJECT_DIR/bin/tools/RunFunctions    # Tutorial run functions

./Allrun.pre

runApplication -s wallFilmRegion decomposePar -region wallFilmRegion
runApplication -s primaryRegion  decomposePar

runParallel $(getApplication)

runApplication -s wallFilmRegion reconstructPar -region wallFilmRegion
runApplication -s primaryRegion  reconstructPar

#------------------------------------------------------------------------------
