#!/bin/sh

currDir=`pwd`
application=`basename $currDir`
case="hartmann"

tutorialPath=`dirname $0`/..
. $tutorialPath/RunFunctions

runApplication blockMesh $case
runApplication $application $case
runApplication sample $case