#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

./Allrun.pre

runApplication $(getApplication)

runApplication foamLog log.boundaryFoam

if [ -e logs/yPlus_0 ]
then
    yPlus=$(awk < logs/yPlus_0 'END{print $2}')
    uPlus=$(awk < logs/uPlus_0 'END{print $2}')

    echo "$yPlus $uPlus" >> ../yPlus_vs_uPlus.xy
fi

#------------------------------------------------------------------------------
