#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

./Allrun.pre

decomposePar -region wallFilmRegion > log.decomposePar.wallFilmRegion 2>&1
decomposePar > log.decomposePar.primaryRegion 2>&1

runParallel reactingParcelFilmFoam 4

reconstructPar -region wallFilmRegion > log.reconstructPar.wallFilmRegion 2>&1
reconstructPar > log.reconstructPar.primaryRegion 2>&1

