#!/bin/sh

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase
rm -rf VTK
rm -rf constant/cellToRegion constant/polyMesh/sets

# -----------------------------------------------------------------------------
