#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

mkdir -p constant/triSurface

cp -f \
    "$FOAM_TUTORIALS"/resources/geometry/terrain.stl.gz \
    constant/triSurface/

restore0Dir

runApplication blockMesh

runApplication decomposePar

runParallel snappyHexMesh -overwrite

find . -iname '*level*' -type f -delete

# Set the initial fields
restore0Dir -processor

runParallel topoSet

runParallel $(getApplication)

runApplication reconstructParMesh -constant

runApplication reconstructPar

runApplication setExprFields -latestTime  ## -load-fields U

runApplication setExprBoundaryFields -latestTime  ## -load-fields '(U)'

#------------------------------------------------------------------------------
