#!/bin/sh
cd ${0%/*} || exit 1                        # Run from this directory
. $WM_PROJECT_DIR/bin/tools/RunFunctions    # Tutorial run functions

# Make dummy 0 directory
mkdir 0

runApplication blockMesh
\cp system/decomposeParDict.hierarchical system/decomposeParDict
runApplication decomposePar

\cp system/decomposeParDict.ptscotch system/decomposeParDict
runParallel snappyHexMesh -overwrite

find . -iname '*level*' -type f -delete

# - Set the initial fields
restore0Dir -processor

runParallel topoSet
runParallel $(getApplication)

runApplication reconstructParMesh -constant
runApplication reconstructPar

#------------------------------------------------------------------------------
