#!/bin/sh
cd ${0%/*} || exit 1                        # Run from this directory
. $WM_PROJECT_DIR/bin/tools/CleanFunctions  # Tutorial clean functions

cleanCase0

rm system/topoSetDict > /dev/null 2>&1

# Remove surfaces and features
rm -f  constant/triSurface/DTC-scaled.stl.gz > /dev/null 2>&1
rm -f  constant/triSurface/DTC-scaled.eMesh  > /dev/null 2>&1
rm -rf constant/extendedFeatureEdgeMesh > /dev/null 2>&1

#------------------------------------------------------------------------------
