#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

runApplication ./makeMesh
restore0Dir
topoSet
setFields
setsToZones -noFlipMap
runApplication $(getApplication)

#------------------------------------------------------------------------------
