#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

(cd background && ./Allclean)
(cd floatingBody && ./Allclean)

# ----------------------------------------------------------------- end-of-file
