#!/bin/sh

# Get application name from directory
application=`basename $PWD`

# Find and source additional functions
tutorialPath=$PWD
while [ ! -f $tutorialPath/CleanFunctions ]
do
    tutorialPath="$tutorialPath/.."
done
. $tutorialPath/CleanFunctions



keepCases="damBreak"
loseCases="damBreakFine"


for case in $keepCases
do
    (cd $case && $tutorialPath/cleanAll)

    if [ "$case" = "damBreak" ] 
    then 
        cp $case/0/gamma.org $case/0/gamma
    fi
done

for case in $loseCases
do
    removeCase $case
done
