#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application name from directory
application="interFoam"

laminarCases="damBreak"
rasCases="damBreak"
lesCases="nozzleFlow2D"

computeCase()
{
    if [ -f Allrun ] ; then
        ./Allrun
    else
        runApplication blockMesh
        runApplication changeDictionary
        runApplication $application
    fi
}

cd laminar
for case in $laminarCases
do
    cd $case
    computeCase
    cd ..
done
cd ..

cd ras
for case in $rasCases
do
    cd $case
    computeCase
    cd ..
done
cd ..

cd les
for case in $lesCases
do
    cd $case
    computeCase
    cd ..
done
cd ..
