#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory
set -x

wclean libso phasesSystem
wclean libso meltingEvaporationModel
wclean libso CompressibleMultiPhaseTurbulenceModels
wclean libso laserDTRM
wclean

# ----------------------------------------------------------------- end-of-file
