#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

targetType=libso
. $WM_PROJECT_DIR/wmake/scripts/AllwmakeParseArguments

wmakeLnInclude massTransferModels
wmake phasesSystem
wmake massTransferModels
wmake CompressibleMultiPhaseTurbulenceModels
wmake laserDTRM
wmake


# ----------------------------------------------------------------- end-of-file
