#!/bin/sh

cd ${0%/*} || exit 1    # run from this directory

. $WM_PROJECT_DIR/bin/tools/RunFunctions  # Tutorial run functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions  # Tutorial clean functions

# Compute test case with different synthetic inflow models
declare -a Models=(
    "reducedDigitalFilter"
    "digitalFilter"
    "DFSEM"
)

# Collect data in 'results' directory
[ -d "results" ] || mkdir results
restore0Dir
runApplication blockMesh

# Compute parallel and collect data
for val in ${Models[@]}; do
  echo "Running the case with the model: $val"
  \rm 0/U*
  \cp 0.orig/U.$val 0/U
  \rm -r constant/boundaryData/inlet
  \cp -r constant/boundaryData/inlet.$val constant/boundaryData/inlet
  runApplication decomposePar
  runParallel pimpleFoam
  gnuplot plot.patch
  gnuplot plot.cell
  mv postProcessing results/postProcessing.$val
  mv stress* results/postProcessing.$val/.
  mv log* results/postProcessing.$val/.
  cleanTimeDirectories
  \rm -rf processor* > /dev/null 2>&1
done

