#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/CleanFunctions      # Tutorial clean functions
#------------------------------------------------------------------------------

cleanCase0

rm -rf constant/triSurface/blob.stl.gz

rm -rf constant/cellAlignments
rm -rf constant/targetCellSize
rm -rf constant/internalDelaunayVertices

(
    cd constant/backgroundMeshDecomposition/polyMesh 2>/dev/null || exit
    rm -f boundary faces neighbour owner points
)

rm -rf snapToSurface?.obj
rm -rf tetsToSnapTo.obj

#------------------------------------------------------------------------------
