#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x

if [ -d "$ParaView_DIR" -a -r "$ParaView_DIR" ]
then
    case "$ParaView_VERSION" in
    3* | git)

        if [ ! -n "${PV_PLUGIN_PATH}" ]
        then
            echo "$0 : PV_PLUGIN_PATH not a valid."
            exit 1
        fi

        wmake libso vtkPV3Readers
        PV3blockMeshReader/Allwmake
        PV3FoamReader/Allwmake
    ;;
    esac
fi

# ----------------------------------------------------------------- end-of-file
