#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

resourcesDir="$FOAM_TUTORIALS"/incompressible/adjointOptimisationFoam/resources

restore0Dir

cp -rf "$resourcesDir"/meshes/sbend/polyMesh/ constant/

runApplication decomposePar

runParallel -s adjointOptimisationFoamFirstPhase $(getApplication)

sed -i 's/endTime           5/endTime           10/g' system/controlDict
sed -i 's/axisAligned/fromFile/g' constant/dynamicMeshDict

runParallel $(getApplication)

runParallel cumulativeDisplacement

#------------------------------------------------------------------------------
