#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

wmakeCheckPwd "$WM_PROJECT_DIR/src" || {
    echo "Error: Current directory is not \$WM_PROJECT_DIR/src"
    echo "    The environment variables are inconsistent with the installation."
    echo "    Check the OpenFOAM entries in your dot-files and source them."
    exit 1
}

set -x

# update OpenFOAM version strings if required
wmakePrintBuild -check || /bin/rm -f OpenFOAM/Make/$WM_OPTIONS/global.? 2>/dev/null

wmakeLnInclude OpenFOAM
wmakeLnInclude OSspecific/$WM_OSTYPE
Pstream/Allwmake

wmake libo  OSspecific/$WM_OSTYPE
wmake libso OpenFOAM

wmake libso lagrangian/basic

wmake libso edgeMesh
wmake libso surfMesh
wmake libso triSurface

# Decomposition methods needed by meshTools
wmake libso parallel/decompositionMethods
wmake libso parallel/metisDecomp

wmake libso meshTools
wmake libso finiteVolume
wmake libso genericPatchFields

wmake libso sampling

wmake libso dynamicMesh
wmake libso dynamicFvMesh
wmake libso topoChangerFvMesh

wmake libso ODE
wmake libso randomProcesses

thermophysicalModels/Allwmake
transportModels/Allwmake
turbulenceModels/Allwmake
lagrangian/Allwmake
parallel/Allwmake
postProcessing/Allwmake
conversion/Allwmake
mesh/Allwmake

wmake libso errorEstimation

fvAgglomerationMethods/Allwmake

wmake libso fvMotionSolver
wmake libso engine

# ----------------------------------------------------------------- end-of-file
