#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase
rm -rf 0

# Remove surface
rm -f constant/triSurface/motorBike.obj.gz

# Reset decomposeParDict
cp system/decomposeParDict.hierarchical system/decomposeParDict

#------------------------------------------------------------------------------
