#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

# Generate mesh if required
[ -d constant/polyMesh ] || ./Allrun.pre

runApplication decomposePar

runParallel $(getApplication)

runApplication reconstructPar -latestTime

#------------------------------------------------------------------------------
