#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/CleanFunctions      # Tutorial clean functions
#------------------------------------------------------------------------------

for subcase in $(./list-worlds)
do
(
    cd "$subcase" || exit
    cleanCase0
    rm -f *_mapped.obj 2>/dev/null
)
done
rm -rf log.* 2>/dev/null

#------------------------------------------------------------------------------
