#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

./Allrun.pre

runApplication setFields

runApplication $(getApplication)

runApplication postProcess -funcs \
    "(minMaxComponents(U) minMaxMagnitude(U))" -latestTime

#------------------------------------------------------------------------------
