#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

restore0Dir

runApplication blockMesh

decompDict="-decomposeParDict system/decomposeParDict.4"

if false
then
    # Simple preparation

    runApplication makeFaMesh

    runApplication decomposePar

else

    # Additional steps (to exercise some functionality)

    runParallel $decompDict -s decompose redistributePar -decompose

    runParallel $decompDict makeFaMesh

    runParallel -s redistribute redistributePar -overwrite
fi

runParallel $(getApplication)

#------------------------------------------------------------------------------
