#define TOK_QUESTION                         1
#define TOK_COLON                            2
#define TOK_LOR                              3
#define TOK_LAND                             4
#define TOK_EQUAL                            5
#define TOK_NOT_EQUAL                        6
#define TOK_LESS_EQ                          7
#define TOK_GREATER_EQ                       8
#define TOK_LESS                             9
#define TOK_GREATER                         10
#define TOK_PLUS                            11
#define TOK_MINUS                           12
#define TOK_TIMES                           13
#define TOK_DIVIDE                          14
#define TOK_PERCENT                         15
#define TOK_NEGATE                          16
#define TOK_NOT                             17
#define TOK_NUMBER                          18
#define TOK_LPAREN                          19
#define TOK_RPAREN                          20
#define TOK_MAG                             21
#define TOK_PI                              22
#define TOK_DEG_TO_RAD                      23
#define TOK_RAD_TO_DEG                      24
#define TOK_EXP                             25
#define TOK_LOG                             26
#define TOK_LOG10                           27
#define TOK_SQR                             28
#define TOK_SQRT                            29
#define TOK_CBRT                            30
#define TOK_SIN                             31
#define TOK_COS                             32
#define TOK_TAN                             33
#define TOK_ASIN                            34
#define TOK_ACOS                            35
#define TOK_ATAN                            36
#define TOK_SINH                            37
#define TOK_COSH                            38
#define TOK_TANH                            39
#define TOK_MAGSQR                          40
#define TOK_FLOOR                           41
#define TOK_CEIL                            42
#define TOK_ROUND                           43
#define TOK_POW                             44
#define TOK_COMMA                           45
#define TOK_ATAN2                           46
#define TOK_HYPOT                           47
#define TOK_MIN                             48
#define TOK_MAX                             49
#define TOK_RAND                            50
#define TOK_BOOL_FALSE                      51
#define TOK_BOOL_TRUE                       52
#define TOK_BOOL                            53
