#define TOK_PLUS                             1
#define TOK_MINUS                            2
#define TOK_TIMES                            3
#define TOK_DIVIDE                           4
#define TOK_NEGATE                           5
#define TOK_NUMBER                           6
#define TOK_LPAREN                           7
#define TOK_RPAREN                           8
#define TOK_PI                               9
#define TOK_DEG_TO_RAD                      10
#define TOK_RAD_TO_DEG                      11
#define TOK_EXP                             12
#define TOK_LOG                             13
#define TOK_LOG10                           14
#define TOK_POW                             15
#define TOK_COMMA                           16
#define TOK_SQR                             17
#define TOK_SQRT                            18
#define TOK_CBRT                            19
#define TOK_SIN                             20
#define TOK_COS                             21
#define TOK_TAN                             22
#define TOK_ASIN                            23
#define TOK_ACOS                            24
#define TOK_ATAN                            25
#define TOK_ATAN2                           26
#define TOK_HYPOT                           27
#define TOK_SINH                            28
#define TOK_COSH                            29
#define TOK_TANH                            30
#define TOK_MIN                             31
#define TOK_MAX                             32
#define TOK_MAG                             33
#define TOK_MAGSQR                          34
#define TOK_FLOOR                           35
#define TOK_CEIL                            36
#define TOK_ROUND                           37
#define TOK_RAND                            38
