#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
export WM_CONTINUE_ON_ERROR=true                    # Optional unit
. ${WM_PROJECT_DIR:?}/wmake/scripts/AllwmakeParseArguments
. ${WM_PROJECT_DIR:?}/wmake/scripts/paraviewFunctions # CMake, PV functions
# -----------------------------------------------------------------------------

warnIncomplete()
{
    echo
    echo "    WARNING: incomplete build of ParaView plugin: $@"
    echo
}

if have_pvplugin_support
then
(
    wmakeLibPv common
    wmakeLibPv blockMeshReader/library
    wmakeLibPv foamReader/library

    unset cmakeOpts cmakeType

    if [ "$targetType" != objects ]
    then
        case "$PARAVIEW_API" in
        (5.[0-6])
            cmakeType="cmakePv"
            ;;
        (*)
            # cmakeType="cmakePvInstall"
            warnIncomplete "(unknown/unsupported version: $PARAVIEW_API)"
            ;;
        esac
    fi

    if [ -n "$cmakeType" ]
    then
        "$cmakeType" $PWD/blockMeshReader "$cmakeOpts" || warnIncomplete "blockMesh"
        "$cmakeType" $PWD/foamReader "$cmakeOpts" || warnIncomplete "OpenFOAM"
    fi
)
fi

#------------------------------------------------------------------------------
