#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

restore0Dir

runApplication blockMesh

runApplication setFields

runApplication topoSet

runApplication decomposePar

runParallel $(getApplication)
