#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/CleanFunctions      # Tutorial clean functions
#------------------------------------------------------------------------------

mv ./-180 temp180
cleanCase

rm -rf 0
rm -f constant/polyMesh/boundary

mv temp180 ./-180

#------------------------------------------------------------------------------
