#!/bin/sh

currDir=`pwd`
application=`basename $currDir`
cases="cylinder pitzDaily"
utility=analyticalCylinder

tutorialPath=`dirname $0`/..
. $tutorialPath/CleanFunctions

for case in $cases
do
    cleanCase $case
    rm -rf $case/0 > /dev/null 2>&1
    cp -r $case/0.org $case/0

    if [ "$case" = "cylinder" ] 
    then
        wclean $case/$utility
    fi
done 


