#!/bin/sh
cd ${0%/*} || exit 1                        # Run from this directory
. $WM_PROJECT_DIR/bin/tools/CleanFunctions  # Tutorial clean functions

cleanCase

rm -rf constant/extendedFeatureEdgeMesh > /dev/null 2>&1
rm -rf constant/triSurface/unit_cube.eMesh > /dev/null 2>&1
rm -rf MeshedSurface*.obj > /dev/null 2>&1

#------------------------------------------------------------------------------
