#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

mkdir -p constant/triSurface

cp -f \
    "$FOAM_TUTORIALS"/resources/geometry/unit_cube.stl.gz \
    constant/triSurface

runApplication surfaceFeatureExtract

runApplication foamyQuadMesh -overwrite

runApplication extrude2DMesh -overwrite polyMesh2D

runApplication checkMesh -allGeometry -allTopology -constant -noZero

#------------------------------------------------------------------------------
